### ISSUE TITLE
Add index property to history state

### ISSUE THREAD

**Issue by XiaopingHu** [vuejs/vue-router#3291] opened 2020-08-10 06:51 UTC
### What problem does this feature solve?
In browse, we can not judge whether it back or forward by history state, because the state only have key property and the key value just is a time string.
if we add index property to state, we can judge.

### What does the proposed API look like?
```javascript
let index = 0

function genStateIndex() {
  return index  ;
}

function getStateIndex() {
  return index
}

//in push-state.js
if (replace) {
  // preserve existing history state as it could be overriden by the user
  const stateCopy = extend({}, history.state)
  stateCopy.key = getStateKey()
  //add follow codes
  stateCopy.index = getStateIndex()
  
  history.replaceState(stateCopy, '', url)
} else {
  history.pushState({
    key: setStateKey(genStateKey()),
    //add
    index: genStateIndex()
  }, '', url)
}
```

**Comment by posva** [comment] 2020-08-10 13:15
There are a few edge cases making this strategy not reliable. But you are free to add your own state to history and use it the way you want. In v4, there is a `position` saved in history to determine if a navigation is forward or backwards but there are cases where it cannot know.

**Comment by posva** [comment] 2020-08-10 13:15
Duplicate of https://github.com/vuejs/vue-router/issues/2571

**Closed as completed by posva** 2020-08-10 13:15 UTC
