### ISSUE TITLE
Add removeRoutes method to dynamically remove named routes

### ISSUE THREAD

**Issue by piotrek-horodenski** [vuejs/vue-router#2543] opened 2018-12-20 17:52 UTC
### What problem does this feature solve?
This may be useful when we want to manage routes that are registered for the user - for instance on logout.

### What does the proposed API look like?
router.removeRoutes(names: string[])

names - array of names of the routes to remove (including child routes)

- removing current route triggers route matching and navigation occurs
- removing a route removes all of its children routes
- removing a child route does not remove its parent route

**Comment by posva** [comment] 2018-12-20 19:12
Duplicate of #1234

**Closed as completed by posva** 2018-12-20 19:12 UTC
