### ISSUE TITLE
路由history和scrollBehavior()函数的冲突

### ISSUE THREAD

**Issue by SILENCEXZL** [vuejs/vue-router#3639] opened 2021-09-19 06:49 UTC
### Version
3.5.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/mystifying-easley-31bky?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
const router = new VueRouter({
  routes ,
  mode:'history',
  scrollBehavior() {
    return {x:0,y:0}
  }
})

### What is expected?
在浏览器输入localhost:8080//////  可以正常访问

### What is actually happening?
显示空白页，控制台报错：
Failed to execute 'replaceState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:8081' and URL 'http://localhost:8081///////'."

---
困扰了我三天的一个问题，希望可以得到解决。是我的使用方式有问题，还是确实是个bug呢？

**Comment by posva** [comment] 2021-09-19 11:31
Duplicate of #2593

**Closed as completed by posva** 2021-09-19 11:31 UTC

**Comment by SILENCEXZL** [comment] 2021-09-20 02:15
oh，thanks.I didn't see that issue before.It seems that you know Chinese？ @posva

**Comment by posva** [comment] 2021-09-27 13:01
Not yet 😆 Give it a few years
