### ISSUE TITLE
Dynamic alias

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vue-router#2408] opened 2018-09-26 13:07 UTC
### What problem does this feature solve?
With a route defined like this: 

```
{
    path: '/404',
    alias: '*',
    name: 'error',
    component: Error
}
```

When a user visit `my-site.com/random-inexisting-url`, the url doesn't change and it displays the error page. (this is what we want)

*** 

Now, how to to do the same with dynamic routes?

Example: 
- there is a route like `my-site.com/pages/:id` 
- the user visits `my-site.com/pages/inexisting-id`. 
- the `id` param is used to fetch an API. If the API returns null, there is no automatic redirection to the error page. 

It is possible to manually redirect to the `/error` page with `router.push({ name: 'error' })` or a navigation guard, but it will change the url to `/error`. 

**Is it possible to keep the original url, but still display the error page?** 

### What does the proposed API look like?
something like `router.aliasTo({name: 'error' })`

**Comment by posva** [comment] 2018-09-26 13:28
Duplicate of #1858

**Closed as completed by posva** 2018-09-26 13:28 UTC

**Comment by francoisromain** [comment] 2018-09-26 14:06
@posva, When I read #1858, I don't understand the same thing I describe here

**Comment by Hoishin** [comment] 2018-09-26 14:46
I think what you want to do is achievable with navigation guard

**Comment by francoisromain** [comment] 2018-09-26 14:52
@Hoishin Could you give an example please?

**Comment by posva** [comment] 2018-09-26 15:41
If you want to keep the url, then you should use a path of `*` instead 🙂 
There is also another FR that may interest you is about replacing the view without changing the URL

**Comment by francoisromain** [comment] 2018-09-26 16:29
> you should use a path of * instead

instead of what?

**Comment by NiackZ** [comment] 2023-10-14 21:37
Any solutions?))
