### ISSUE TITLE
In the hash mode, press the browser back button is not work

### ISSUE THREAD

**Issue by ml-milkmidi** [vuejs/vue-router#933] opened 2016-11-24 09:51 UTC
sample code
https://router.vuejs.org/en/advanced/meta.html

const router = new VueRouter( {
mode: 'hash' // back button not work
//mode: 'history' // it's work
})

router.beforeEach((to, from, next) => {
console.log(to); // not toggle log ????????????
  if (to.matched.some(record => record.meta.requiresAuth)) {
    if (!auth.loggedIn()) {
      next({
        path: '/login',
        query: { redirect: to.fullPath }
      })
    } else {
      next()
    }
  } else {
    next() // make sure to always call next()!
  }
})

Thanks

**Comment by fnlctrl** [comment] 2016-11-24 10:20
Thanks for filling this issue. Closing as it's a duplicate of #853

**Closed as completed by fnlctrl** 2016-11-24 10:20 UTC
