### ISSUE TITLE
replaceState Error when path starts with // and scrollBehavior is set

### ISSUE THREAD

**Issue by yegorLitvinov** [vuejs/vue-router#2593] opened 2019-01-22 14:29 UTC
### Version
3.0.2

### Reproduction link
[https://github.com/yegorLitvinov/vue-router-bug](https://github.com/yegorLitvinov/vue-router-bug)

### Steps to reproduce
Set scrollBehavior property in router config. Put two forward slashes into beginning of the url (e.g. http://localhost:8081//about)

### What is expected?
No errors in console

### What is actually happening?
In firefox: SecurityError: The operation is insecure.
In Chrome: Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://about/' cannot be created in a document with origin 'http://localhost:8081' and URL 'http://localhost:8081//about'

**Comment by posva** [comment] 2019-01-22 14:43
It looks like we should sanitize the beginning of the URL so it doesn't contain trailing slashes but I'm still unsure about it. I will have to search a bit more

**Comment by luatnd** [comment] 2019-05-21 03:41
I faced this issue too.

**Steps to reproduce:**

0. Build
1. deploy to `primary.domain.com`
2. deploy to `secondary.domain.com`
3. Add `<base href="https://primary.domain.com" target="_blank">` into `secondary.domain.com`
4. Access url `secondary.domain.com` then saw this issue

**Debug info**
```
vue: 2.5.17
vue-router: 3.0.6,
```


`vue-router/dist/vue-router.js:1550`
```javascript

function setupScroll () {
  // Fix for #1585 for Firefox
  // Fix for #2195 Add optional third attribute to workaround a bug in safari https://bugs.webkit.org/show_bug.cgi?id=182678
  window.history.replaceState({ key: getStateKey() }, '', window.location.href.replace(window.location.origin, '')); // ======> This line cause the issue
  window.addEventListener('popstate', function (e) {
    saveScrollPosition();
    if (e.state && e.state.key) {
      setStateKey(e.state.key);
    }
  });
}
```

**The temporary solution:**
Comment the bellow line to avoid setupScroll => Then implement scrollBehavior by your self on route changed:
```javascript
const Router = new VueRouter({
    scrollBehavior: () => ({ y: 0 }), // ===> Comment this line to avoid setupScroll => Then implement scrollbehavior by your self on route change.
    routes: ...,
  })
```
If you ignore `scrollBehavior` key, setupScroll() will not be executed.

Hope this help!

**Comment by bkarlson** [comment] 2019-11-07 15:28
wow, thanks for this issue. Just faced this as well, exact same scenario as @luatnd desribed.

**Comment by ralf57** [comment] 2019-11-20 09:30
@posva any news about this?

**Comment by Aigrefin** [comment] 2020-02-03 09:45
Hi,
The temporary solution from @luatnd doesn't always work.
Any progress on this bug ?

**Comment by Madd0g** [comment] 2020-02-21 08:36
I'm also seeing this problem, but with $ sign in the querystring.

**Comment by mattheyan** [comment] 2020-05-08 15:51
I'm experiencing this problem as well.

In my case the original URL looks like `https://site.com//?x=y`, which results in calling `replaceState` with `//?x=y` as the URL. I put in a place a workaround to detect the situation and trim the duplicate `/` before initializing the router.

This comment has some useful info: https://github.com/ReactTraining/react-router/issues/3184#issuecomment-293370088
Note that although I'm linking to an issue in a react package, I am actually experiencing this issue in vue router. 😛  It seems this same issue is referenced in lots of different contexts, so it must be a common / easy problem to run into. Either that or different libs have based their browser history code on the same original source.

**Comment by HaydenBruin** [comment] 2020-12-08 20:56
I was having this issue as well. The only thing I was using scrollBehavior for was to scroll the user to the top of the page.

Before:

```
const router = new VueRouter({
  base: process.env.BASE_URL,
  routes,
  scrollBehavior() {
    return { x: 0, y: 0 };
  },
});
```

After: 

```
const router = new VueRouter({
  base: process.env.BASE_URL,
  routes,
});

router.afterEach(() => {
  window.scrollTo(0, 0);
});
```

**Comment by posva** [comment] 2021-04-14 17:50
In v4 this is fixed by using the full URL: https://github.com/vuejs/vue-router-next/blob/master/src/history/html5.ts#L220

I think it's worth adding the same fix here

**Closed as completed** 2021-10-26 14:45 UTC
Labels: bug, fixed on 4.x

**Comment by snoozbuster** [comment] 2021-12-15 02:59
hey @posva - I don't think this is closed by the linked PR. That PR does fix the issue if the navigation comes from a router-link or programmatic call to `replace()` or `push()` - but the issue still remains if the page is hard-loaded with a double-slash in the pathname.

I think the issue is caused by [this line](https://github.com/vuejs/vue-router/blob/dev/src/util/scroll.js#L25), as @mattheyan mentioned. When the pathname contains multiple leading slashes, the `absoluteUrl` with the scheme and hostname excised contains a leading double slash, which is reinterpreted as an actual absolute URL (with current scheme, host and path) instead of a path on the current domain. `cleanPath` isn't ever called on this URL, so the fix in that PR doesn't actually fix this issue.

I imagine the easiest way to fix this is to update the code to call cleanPath here. assuming that's the correct solution, I've taken the liberty of opening a PR for it: https://github.com/vuejs/vue-router/pull/3679 (with included e2e test)
