### ISSUE TITLE
router.resolve does not use current route by default

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue-router#2385] opened 2018-09-14 04:59 UTC
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/df4Lnuw6/698/](http://jsfiddle.net/df4Lnuw6/698/)

### Steps to reproduce
- Click the link.
- Click the button.

### What is expected?
No warning to be shown.

### What is actually happening?
A warning is shown saying that the id param was not provided. The [docs](https://router.vuejs.org/api/#router-resolve) mention that the current route will be used if omitted.

**Comment by clintonyeb** [comment] 2018-09-16 14:56
In current implementation, this is how the resolve method is implemented [https://github.com/vuejs/vue-router/blob/dev/src/index.js#L177](https://github.com/vuejs/vue-router/blob/dev/src/index.js#L177) :

```js
resolve (
    to: RawLocation,
    current?: Route,
    append?: boolean
  ): {
    location: Location,
    route: Route,
    href: string,
    // for backwards compat
    normalizedTo: Location,
    resolved: Route
  } {
    const location = normalizeLocation(
      to,
      current || this.history.current,
      append,
      this
    )
    const route = this.match(location, current)
    const fullPath = route.redirectedFrom || route.fullPath
    const base = this.history.base
    const href = createHref(base, fullPath, this.mode)
    return {
      location,
      route,
      href,
      // for backwards compat
      normalizedTo: location,
      resolved: route
    }
}
```

I am thinking the issue is coming from from  line 195:
` const route = this.match(location, current)`

I am proposing this new implementation:

```js
resolve (
    to: RawLocation,
    current?: Route,
    append?: boolean
  ): {
    location: Location,
    route: Route,
    href: string,
    // for backwards compat
    normalizedTo: Location,
    resolved: Route
  } {
    current = current || this.history.current

    const location = normalizeLocation(
      to,
      current,
      append,
      this
    )
    const route = this.match(location, current)
    const fullPath = route.redirectedFrom || route.fullPath
    const base = this.history.base
    const href = createHref(base, fullPath, this.mode)
    return {
      location,
      route,
      href,
      // for backwards compat
      normalizedTo: location,
      resolved: route
    }
}
```

Will love to receive feedbacks..

**Comment by posva** [comment] 2018-09-16 15:19
yeah, I remember I did this but somehow never committed the code nor created a PR...

**Comment by clintonyeb** [comment] 2018-09-16 15:23
Thanks :)

**Closed as completed** 2019-03-28 17:20 UTC
Labels: bug, has PR
