### ISSUE TITLE
Wrong definition of interface RouteConfig in router.d.ts

### ISSUE THREAD

**Issue by Maorey** [vuejs/vue-router#2883] opened 2019-08-12 14:04 UTC
### Version
3.1.2

### Reproduction link
[https://github.com/vuejs/vue-router/blob/5141def3a21da479c2858c0d70db3cb438c3b7d0/types/router.d.ts#L3](https://github.com/vuejs/vue-router/blob/5141def3a21da479c2858c0d70db3cb438c3b7d0/types/router.d.ts#L3)

### Steps to reproduce
``` TypeScript
import { Component, CreateElement, RenderContext } from 'vue'
import Router from 'vue-router'

const functional: Component = {
  functional: true,
  render(createElement: CreateElement, context: RenderContext) {
    return createElement('div', context.data, context.children)
  },
}

new Router({
  mode: 'hash',
  routes: [
    {
      path: `/functional`,
      name: 'functional',
      component: functional,
    }
  ]
})
```

### What is expected?
Correct

### What is actually happening?
type Error

---
Should be:
``` TypeScript
/* 1 */ import Vue, { Component, PluginFunction } from 'vue'
/* 2 */
/* 3 DELETE */ type Component = ComponentOptions<Vue> | typeof Vue | AsyncComponent
```

**Comment by posva** [comment] 2019-08-12 17:57
Duplicate of https://github.com/vuejs/vue-router/pull/2647

**Closed as completed by posva** 2019-08-12 17:57 UTC
