### ISSUE TITLE
the laster router record obtained by getRoutes is wrong after use addRoute(parentName, route)

### ISSUE THREAD

**Issue by FoxDaxian** [vuejs/vue-router#3686] opened 2021-12-20 12:19 UTC
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/bitter-dew-ie45g?file=/src/router/index.ts)

### Steps to reproduce
you can click reproduction link and open the console panel to see the flattened router record.

### What is expected?
Get correct router record by `getRoutes or something else` after `addRoute(parentName, route)` like below:

```javascript
const routes = [
    {
        path: '/',
        name: 'parent',
        component: parentComponent
    }
];

router.addRoute('parent', {
    path: '/son',
    name: 'son',
    component: sonComponent
})

// correct result

[{
    children: [ {
        // son component
    } ],
    name: "parent".
    path: "/",
    .....
}]

```

### What is actually happening?
```javascript
// flattened array
[{
    children: [ there is empty.. ],    // <---- 
    name: "parent".
    path: "/",
    .....
},
{
    children: [  ],
    name: "son".
    path: "/son",
    .....
}]

```

---
not sure weather i am wrong, but according [addroute](https://next.router.vuejs.org/api/#addroute) and [getroutes](https://next.router.vuejs.org/api/#getroutes),  this is what I could thought.
and need help~

**Comment by posva** [comment] 2021-12-20 13:22
Duplicate of https://github.com/vuejs/vue-router-next/issues/1252

**Closed as completed by posva** 2021-12-20 13:22 UTC
