### ISSUE TITLE
Export RouterLink and RouterView component

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vuejs/vue-router#3729] opened 2022-03-01 05:08 UTC
### What problem does this feature solve?

https://github.com/vuejs/create-vue using local component registry in vue 3 template.
 
see https://github.com/vuejs/create-vue-templates/blob/284fcf591115e5cf39e4461e2fd4cd2c5ea009bb/typescript-router/src/App.vue#L2

```ts
import { RouterLink, RouterView } from 'vue-router'
```

We can import RouterLink and RouterView in vue-router v4

I think we should also export it in vue-router v3 . 

It will help typescript users and jsx users a lot. We can get better type information with this.

And also, we use lint rule https://eslint.vuejs.org/rules/no-undef-components.html

```js
{
    'vue/no-undef-components': [
        'error',
        {
            ignorePatterns: [
                /**
                 * Waiting for vue-router
                 */
                'RouterView',
                'RouterLink', 
            ],
        },
    ]
}
```

If vue-router v3 can export  RouterLink and RouterView, we can simplified configuration.

### What does the proposed API look like?
```ts
import { RouterLink, RouterView } from 'vue-router'

const { RouterLink, RouterView } = require('vue-router')
```

**Comment by xiaoxiangmoe** [comment] 2022-03-01 07:05
In cjs, we can use

```js
const VueRouter = require('vue-router')
const { RouterLink, RouterView } = VueRouter
```

In esm, we can use
```js
import VueRouter from 'vue-router'
const { RouterLink, RouterView } = VueRouter
// or
import { RouterLink, RouterView } from 'vue-router'
```
---

For old cjs user, we can still use `const VueRouter = require('vue-router')`
For old esm user, we can still use `import VueRouter from 'vue-router'`

So it will not break current users.

**Comment by posva** [comment] 2022-03-01 17:24
Duplicate of https://github.com/vuejs/vue-router/issues/1534

**Closed as completed by posva** 2022-03-01 17:24 UTC
