### ISSUE TITLE
router.back and router.go can pass arguments

### ISSUE THREAD

**Issue by 1593292349** [vuejs/vue-router#3817] opened 2022-12-29 05:11 UTC
### What problem does this feature solve?
Imagine this scenario:

1.I go back from a child page to a parent page 

2.The parent page has a list that needs to be refreshed based on the status returned by the child pages 

3.I don't want to use pinia to store global state. Because many pages need to return some different information. 

### What does the proposed API look like?
back(params:Record<string,any>):void
go(delta:number,params:Record<string,any>):void

**Comment by posva** [comment] 2023-01-03 08:28
Duplicate of https://github.com/vuejs/router/issues/1646

**Closed as not planned by posva** 2023-01-03 08:28 UTC
