### ISSUE TITLE
[route-view] keep-alive and transition throws exception

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue-router#270] opened 2015-12-07 09:42 UTC
When keep-alive and transition are used together, the following exception is thrown:
```
Uncaught TypeError: this.op is not a function
  p$1.leaveDone @ vue.common.js:5444
  (anonymous function) @ vue.common.js:211
  onEnd.pendingCssCb @ vue.common.js:5570
```

On the very first transition, everything is fine. The following transition will throw the above exception.
This only happens when both attributes are used on route-view component.

**Comment by amirrustam** [comment] 2016-01-10 06:01
@oliverzy Can you provide a some code that reproduces this?

**Comment by yyx990803** [comment] 2016-01-13 21:47
As of 0.7.8 I cannot reproduce this. Closing, feel free to reopen if you can provide a reproduction in 0.7.8.

**Closed by yyx990803** 2016-01-13 21:47 UTC
