### ISSUE TITLE
Is it possible change url but dont render component by vue-router now?

### ISSUE THREAD

**Issue by achen224** [vuejs/vue-router#988] opened 2016-12-06 01:45 UTC
I have 2 routes like:

```
{ path: '/gallery', component: require('components/A') },
{ path: '/gallery/:id', component: require('components/B') },
```

when user go /gallery/:id from outside, it will render component B
but when user go form my webside(like /gallery -> /gallery/:id)
I want change url but render component in lightbox component not router-view

I use like below now

```
{
      path: '/gallery/:id',
      component: require('components/B'),
      beforeEnter: (to, from, next) => {
        if (from.matched.length) {
          history.pushState({}, null, to.path)
        } else {
          next()
        }
      }
}
```

is it possible change url but dont render component by vue-router ?
just like backbone router trigger in router-link, router.push & router.replace

Thx

**Comment by JounQin** [comment] 2016-12-06 04:14
https://router.vuejs.org/en/essentials/navigation.html

`router.replace(location)` should work, doesn't it?

**Comment by achen224** [comment] 2016-12-06 04:42
It does not...

router.replace just like push...but replace history
it will render component in render-view

Thx

**Comment by simplesmiler** [comment] 2016-12-06 10:03
Appears to be duplicate of https://github.com/vuejs/vue-router/issues/703, please reopen if I'm wrong.

**Closed as completed by simplesmiler** 2016-12-06 10:03 UTC
