### ISSUE TITLE
Routing doesn't work with IE 11 : URL change, back and forward buttons

### ISSUE THREAD

**Issue by Krabi** [vuejs/vue-router#1985] opened 2018-01-12 10:16 UTC
### Version
3.0.1

### Reproduction link
[http://cant-be-created](http://cant-be-created)

### Steps to reproduce
1. Create project with : vue init webpack vuejs-webpack

2. Add some router components in src/router/index.js as:
...
import HelloWorld from '@/components/HelloWorld'
import HelloWorld2 from '@/components/HelloWorld2'
...
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {
      path: '/example2',
      name: 'HelloWorld2',
      component: HelloWorld2
    }

3. Copy component in src/components/HelloWorld.vue into new src/components/HelloWorld2.vue

Change names and a content a bit.

4. Add devDependencies (Currenlty this is not clear for me) into package.json:
    "babel-polyfill": "^6.26.0",
    "es6-promise": "^4.2.2",
    "babel-preset-es2015": "^6.24.1",

5. .babelrs change as:
   ...
   "stage-2",
   "es2015"
   ...

6. src/main.js as:
import Vue from 'vue'
import App from './App'
import router from './router'

import es6Promise from 'es6-promise'
es6Promise.polyfill()
...

7. build/webpack.base.conf as:
...
const babelPolyFill = require("babel-polyfill")
...
entry: ["babel-polyfill", "./src/main.js"],
...

8. npm install && npm run build && npm run dev

9. Open IE 11 and copy paste to URL bar http://localhost:8080/#/

10. Append into url: example2 and hit enter

11. NB!!! Nothing happens. Old page is visible. Should show second page content.

13. Click IE refresh: site is now visible

14. NB!!! Click back button: nothing happens. Second page is visible.

15. Click IE refresh: first page is now visible.

16. FF for example works fine with same solution.

### What is expected?
Url  hash (#) part shpould change compponents for hash.

### What is actually happening?
Nothing happens on url change IN IE. FF for example works fine.

**Comment by Krabi** [comment] 2018-01-12 11:15
Also same with simplest code:
```
<!DOCTYPE html>
<html>
    <head>
        <title>VueJS simplest</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=11; IE=edge;" />
    </head>
    <body>
        <div id="app">
            <router-view></router-view>
        </div>
        <script src="https://unpkg.com/vue@2.5.13/dist/vue.js"></script>
        <script src="https://unpkg.com/vue-router@3.0.1/dist/vue-router.js"></script>
        <script>
            var root, foo, bar, routes, router, app;
            root = {template: '<div>root</div>'};
            foo = {template: '<div>foo</div>'};
            bar = {template: '<div>bar</div>'};
            routes = [
                {path: '/', component: root},
                {path: '/foo', component: foo},
                {path: '/bar', component: bar},
                {path: '*', redirect: '/'}
            ];
            router = new VueRouter({
                routes: routes
            });
            app = new Vue({router: router}).$mount('#app');
        </script>
    </body>
</html>

```

**Comment by posva** [comment] 2018-01-12 14:04
Duplicate of #1849

**Closed as completed by posva** 2018-01-12 14:04 UTC
