### ISSUE TITLE
Can scrollBehaviour support to specify scroll container?

### ISSUE THREAD

**Issue by kamilic** [vuejs/vue-router#3481] opened 2021-03-04 02:52 UTC
### What problem does this feature solve?
Our vue app uses a fixed height `<div>` as frame container to load all pages inside, like following snippet:
```html
<div style="
     height: 100%; 
     width: 100%;
     position: fixed;
     overflow-x: hidden;
     overflow-y: scroll;
">
     <vue-router />
</div>
```

I wanted to use `scrollBehaviour` to handle page navigation's `scrollTop`, but it did't work.
And also I found that vue-router set scrollTop by using `window. scrollTo` method at [here](https://github.com/vuejs/vue-router/blob/3e9739a01824d776d179ca8667765dab0ccc7699/src/util/scroll.js#L165).

So I have this idea. For example,  provides a `scrollBehaviourContainer: "#id"` to make it works?

### What does the proposed API look like?
```typescript
new VueRouter({
     scrollBehaviour(to, from, position) {
         return position;
     },
     scrollBehaviourContainer: "#el"
});
```

**Comment by posva** [comment] 2021-03-04 10:14
Duplicate of https://github.com/vuejs/vue-router/issues/1187

Right now you can still manually call scroll inside scrollBehavior and return nothing

**Closed as completed by posva** 2021-03-04 10:14 UTC

**Comment by kamilic** [comment] 2021-03-05 07:32
> Duplicate of #1187
> 
> Right now you can still manually call scroll inside scrollBehavior and return nothing

got it, thanks.
