### ISSUE TITLE
Full support for anchor tags

### ISSUE THREAD

**Issue by Overdrivr** [vuejs/vue-router#2074] opened 2018-02-26 07:57 UTC
### What problem does this feature solve?
Anchor tags cannot be implemented correctly in the current state of things. There are a few techniques to hack a way around, but none of them seem to cover all the following cases:

- Paths with anchors should always lead to the anchor if reached multiple times (currently, only the first time works, even by refreshing the page)
- Anchor tags urls should be shareable (users should be capable of bookmarking/sharing URLs, in a way that the URL will lead them back directly to the anchor)

AFAIK, there two solutions currently that partially support those requirements: [vue-router Scroll behavior](https://router.vuejs.org/en/advanced/scroll-behavior.html) that does not support first requirement in a robust manner, and [vue-scrollto](https://github.com/rigor789/vue-scrollto) that does not support second requirement since it's just scrolling without any sense of routing/url.

### What does the proposed API look like?
The API is already there, using the hash field

```
<router-link :to="{name: 'SomeVue', hash:'#anchor'}">Link to anchor</router-link>

// or

<a href="/somevue#anchor>Link to anchor</a>
```

```
<div id="anchor">Anchor</div>
```

We only need to implement the proper behavior for supporting use cases presented above.

**Comment by posva** [comment] 2018-02-26 11:01
Duplicate of #1668

**Closed as completed by posva** 2018-02-26 11:01 UTC
