### ISSUE TITLE
vue-router force full page redirect

### ISSUE THREAD

**Issue by 719media** [vuejs/vue-router#2354] opened 2018-08-16 20:15 UTC
### What problem does this feature solve?
Sometimes, I have pages for which I have to place third party scripts which do not have any safe teardown method. I don't want behavior from these scripts to pollute other areas of the application, but I'd still like to use vue-router to control the loading of the page, as well as redirecting TO the page. I would like to have routing leaving this page perform a full page redirect (window.location).

### What does the proposed API look like?
An attribute to force router-link to perform a window.location redirect instead. I'm not sure of the best term for the attribute, but for example:
`<router-link :to="{name: 'test'}" refresh />` #will use window.location = '/test';

I suppose this could just exist in user-land via a component wrapper over the top of router-link, but this seems like it would be a minor change so I present it for author review.

Thank you

**Comment by posva** [comment] 2018-08-16 20:37
Duplicate of #1280

**Closed as completed by posva** 2018-08-16 20:37 UTC

**Comment by 719media** [comment] 2018-08-30 23:13
For anyone coming here looking for a specific solution to the problem I outlined (IMO not *quite* the same thing as the duplicate marked external links issue), here's how I did it.

For all routes that contained external DOM modifying pixels I wanted to avoid persisting throughout other routes, I just pasted in a meta value like

```
{
  path: '/invite-accept',
  name: '/some-route',
  component: someComponent,
  meta: {
    windowRedirectAfter: true,
  }
}
```

and then, in the beforeEach property of the vue-router:

```
yourRouterObject.beforeEach((to, from, next) => {
  //this will recursively go up from child to parent, useful if utilizing children routes. otherwise, you don't need it
  let matchedObject = from.matched.slice().reverse().find(r => r.meta && r.meta.hasOwnProperty('windowRedirectAfter'));

  if(matchedObject) {
    if(matchedObject.meta.windowRedirectAfter === true) {
      window.location.href = to.fullPath;
      return;
    }
  }
  next();
});
```

And now, the redirect is handled by window.location instead of vue-router.

**Comment by dynamite-ready** [comment] 2018-11-07 13:08
This should really be a built in attribute.

**Comment by nanlei2000** [comment] 2018-11-22 11:47
here is my solution:
create a `relaod.vue` and give it a route name `reload` : 
`<template> 
  <div></div>
</template>
<script>
export default {
  created() {
    this.$router.push(this.$route.query.path)
  }
}
</script>`
then in the sidebar component:
`const path = xxx
this.$router.push({ name: 'reload', query: { path } })`
this `relaod.vue` should be the child of the basic layout component in order to prevent the whole page refreshing.

**Comment by ryannmedina** [comment] 2019-04-12 00:14
Thanks for posting your solution @719media. We ran into the same problem today. That is one of our components uses xterm.js and it just stuck to the DOM. Your solution did the trick!
