### ISSUE TITLE
How to use transition when router matched?

### ISSUE THREAD

**Issue by rayzang8** [vuejs/vue-router#462] opened 2016-04-13 10:08 UTC
I can't write transition on router-view like `<router-view` transition ="fade"></router-view>`

so, how to use transition on this case？

**Comment by sagaio** [comment] 2016-04-13 14:41
Transitions are supported in `<router-view></router-view>`. This is a working example from my code:
`<router-view transition="fade" transition-mode="out-in" class="animated"></router-view>` using [Animate.css](https://github.com/daneden/animate.css) and my transition registered as this:
`Vue.transition('fade', { enterClass: 'fadeIn', leaveClass: 'fadeOut'})`
It's also stated in the documentation: http://vuejs.github.io/vue-router/en/view.html

**Comment by rayzang8** [comment] 2016-04-15 06:16
Thank you sagaio!
And I found the router configuration "transitionOnLoad" for this case

**Comment by Wipsly** [comment] 2016-06-29 10:29
Where should I put this line?

Vue.transition('fade', { enterClass: 'fadeIn', leaveClass: 'fadeOut'}) 

I want the transition for all of my routes.

**Comment by aguegu** [comment] 2016-07-01 06:54
@Wipsly just in the `main.js`, if you create the project by vue-cli.

**Comment by fnlctrl** [comment] 2016-08-17 15:34
Closing since the issue is resolved.

**Closed by fnlctrl** 2016-08-17 15:34 UTC

**Comment by jamesduan** [comment] 2017-05-17 06:59
very nice!
