### ISSUE TITLE
not respect <base >  tag

### ISSUE THREAD

**Issue by sabakugaara** [vuejs/vue-router#1426] opened 2017-05-17 09:51 UTC
### Version
2.5.3

### Reproduction link
[https://output.jsbin.com/yivetu/](https://output.jsbin.com/yivetu/)

### Steps to reproduce
click the `index` href

### What is expected?
Index url should be: https://www.example.com/

now it is: https://www.example.com/https:/www.example.com/news/index.html/

### What is actually happening?
vue-router can't parse base url 

---
This example is from the html spec about `base` tag https://html.spec.whatwg.org/multipage/semantics.html#the-base-element

>In this example, a base element is used to set the document base URL:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>This is an example for the &lt;base&gt; element</title>
        <base href="https://www.example.com/news/index.html">
    </head>
    <body>
        <p>Visit the <a href="archives.html">archives</a>.</p>
    </body>
</html>
```
> The link in the above example would be a link to "https://www.example.com/news/archives.html".

If the `archives's` href start with `/`, the link would be a link to "https://www.example.com/archives" (whithout `/news/`) . And `vue-router` now doesn't support set base with: `https://www.example.com/news/index.html`.

some other maybe related discussions: https://github.com/ReactTraining/history/issues/94

**Comment by sabakugaara** [comment] 2017-05-17 09:54
need some help thanks!

Search Engine's page cache will inject `<base>` tag for every cached page, but when I add route rule: `*` for 404 match, when view page cache, it will always be 404

**Comment by LinusBorg** [comment] 2017-05-17 10:39
This seems to be a feature request, not a bug report.

**Comment by sabakugaara** [comment] 2017-05-17 14:11
If modify that, it maybe a breaking change https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L194, but work right!

**Comment by posva** [comment] 2017-05-17 14:18
At the moment, you can specify `base: '/news/index.html'` as a workaround. Maybe we should check for starting urls when reading the `base` tags and strip that off with something like `/^(?:https?:)?\/\/[^\/]+/`

**Comment by sabakugaara** [comment] 2017-05-18 01:37
@posva thanks for your advice, in my case, I can't control the value of the base href, it was added by search engine, e.g:

vue-router page cache: https://webcache.googleusercontent.com/search?q=cache:PKjSDLmsED8J:https://github.com/vuejs/vue-router+&cd=1&hl=zh-CN&ct=clnk&lr=lang_en

in console:
```
console.log(document.baseURI); // output: https://github.com/vuejs/vue-router (baseURI same as base )
```

**Comment by posva** [comment] 2017-05-18 10:30
After searching a bit, this looks like there will be a problem with Google cache because the base tag is pointing to `https://vue-hn.now.sh/top` but it should be `https://vue-hn.now.sh/`. One fix for this is to ignore the base tag if it doesn't start with `/` but it may be breaking other things...

**Comment by sabakugaara** [comment] 2017-05-18 12:50
the most desirable thing is respect `base` tag and work well, I would like to submit a PR for this

**Closed as completed** 2017-06-16 15:55 UTC
Labels: improvement
