### ISSUE TITLE
It's a bug?

### ISSUE THREAD

**Issue by spivet** [vuejs/vue-router#1041] opened 2016-12-22 08:04 UTC
### Vue.js / vue-router versions
2.1.0 / 2.1.1

### Reproduction Link
http://jsbin.com/jayokucufo/1/edit?html,js,output

### Steps to reproduce
1 Click the links on the jsbin;
2 Click the three button; 
3 you'll soon see where it goes wrong .
### What is Expected?
Only the button which be clicked should be activated.

### What is actually happening?
But when I click the button `/user/quiz`, the button `/user/quizSummary` also be activated

**Comment by rpkilby** [comment] 2016-12-22 08:10
Is this a duplicate of #1014?

**Comment by posva** [comment] 2016-12-22 08:19
You need to use the `exact` match: http://router.vuejs.org/en/api/router-link.html

**Closed as completed by posva** 2016-12-22 08:19 UTC
