### ISSUE TITLE
Subroutes not working properly once a top level route has changed (potential bug I think)

### ISSUE THREAD

**Issue by aaronjpitts** [vuejs/vue-router#245] opened 2015-11-23 17:57 UTC
Hi guys,

I have some weird behaviour with an SPA I'm developing. I have uploaded a demo to show you the problem, if you go here: http://dev.aaronpitts.ch/ and click the dashboard link in the top right, in the main dashboard page you will see there is a "You're acting as" toggle which toggles a sub route, this works fine, but if you click back to the homepage route (by clicking the logo in the top left) and then click back to the dashboard, the toggle of the subroutes no longer works. I've noticed the subroutes get stuck on what they were left on previously. This only seems to happen when changing from the dashboard route to another top level route, i.e. the homepage route (/). Below is my entry file with my route mapping.

    import Vue from 'vue'

        import Router from 'vue-router'
        import Resource from 'vue-resource'
        import app from './components/app.vue'
        import homePage from './views/homePage.vue'
        import becomeAHost from './views/becomeAHost.vue'
        import dashboard from './views/dashboard/dashboard.vue'
        import dashboardIndex from './views/dashboard/dashboardIndex.vue'
        import dashboardHostIndex from './views/dashboard/dashboardHostIndex.vue'
        import dashboardTenantIndex from './views/dashboard/dashboardTenantIndex.vue'

        // install router
        Vue.use(Router)
        Vue.use(Resource)

        new Vue({
          el: 'body'
        })

        // routing
        const router = new Router({
          history: true
        })

        router.map({
          '/': {
            component: homePage
          },
          '/become-a-host': {
            component: becomeAHost
          },
          '/dashboard': {
            component: dashboard,
            subRoutes: {
              '/as': {
                component: dashboardIndex,
                subRoutes: {
                  '/host': {
                    component: dashboardHostIndex
                  },
                  '/tenant': {
                    component: dashboardTenantIndex
                  }
                }
              }
            }
          }
        })

        router.beforeEach(function () {
          window.scrollTo(0, 0)
        })

        router.redirect({
          '*': '/',
          '/dashboard': '/dashboard/as/host'
        })

        router.start(app, '#app')

What is the problem, is this a potential bug where the subroutes are getting stuck?

Many thanks

**Comment by GuillaumeLeclerc** [comment] 2016-01-11 08:59
I made some tests and I remarked something strange. The afterEach hook is called but not the hooks on the components (detach and attach). It must be a bug somewhere for sure.

**Comment by amirrustam** [comment] 2016-01-12 01:54
@GuillaumeLeclerc it's hard to help without seeing the components of your code. Could you provide a jsFiddle that reproduces the issue?

**Comment by GuillaumeLeclerc** [comment] 2016-01-12 08:17
I tried but sadly I was not able to reproduce it in a simple jsFiddle. I will try to debug it this week and might do a pull request as it must be a bug (there is no reason a transition finish and no component gets detached).

If I cant figure it out, I'll take the huge code base and shrink it progressively to get the smallest JsFiddle possible

**Comment by GuillaumeLeclerc** [comment] 2016-01-17 15:35
This issue can be close it is the same as #334

**Closed** 2016-01-21 17:07 UTC
