### ISSUE TITLE
subroutes lazyload path problem

### ISSUE THREAD

**Issue by transtone** [vuejs/vue-router#464] opened 2016-04-13 23:28 UTC
https://github.com/vuejs/vue-router/blob/dev/example/advanced/route-config.js#L39
when replace this line from 
```component: require('./components/inbox/index.vue'),``` 
to
```component: (resolve) => require(['./components/inbox/index.vue'], resolve),```
it does not work. 

but change this line :
https://github.com/vuejs/vue-router/blob/dev/example/advanced/route-config.js#L10
to
```component: (resolve) => require(['./components/about.vue'], resolve)```
it works.

it seems a path error, the browser try to find:
``` localhost:8080/inbox/message/8.example.build.js ``` 
but webpack build file like this: 

``` localhost:8080/8.example.build.js ``` 
so can't find the file.

these issues does not show us the way to solve it.
https://github.com/vuejs/vue-router/issues/366
https://github.com/vuejs/vue-router/issues/326

**Comment by transtone** [comment] 2016-04-18 02:59
Is there a lazyload example to show how it works in subRoutes?

**Comment by LinusBorg** [comment] 2016-06-01 19:34
@transtone IT sound to me like an issue with webpack rather than vue-router itself. 

I currently can't clone this repo and run the example so could you try setting the webpack option for `publicPath' to '/'`:
```
output: {
    path: './example/advanced',
    publicPath: '/',                             // add this line
    filename: 'example.build.js'
  },
```

**Comment by transtone** [comment] 2016-06-12 03:25
I just git clone vue-router && npm i && npm runscript serve-example

I open this issue just want a example for lazyload, so please send a pr to fix this?

**Comment by LinusBorg** [comment] 2016-06-12 08:27
As I suspected, adding `publicPath: '/' ` to the webpack config solves this.

<img width="300" src="https://cloud.githubusercontent.com/assets/1444526/15989989/1c22e7b6-3088-11e6-9c96-57cc64d12c5b.png">

<img width="644"src="https://cloud.githubusercontent.com/assets/1444526/15989983/0294588e-3088-11e6-8435-3fd86236a231.png">

So it's not an error per se, as the example was not laid out for lazy loading routes, but I think I will issue a small pull request when I get home to make the webpack config more solid.

**Comment by fnlctrl** [comment] 2016-08-17 15:34
This is caused by webpack-dev-server requiring `publicPath` to be set, for code splitting to work properly. 
Closing since the solution is provided above.

**Closed by fnlctrl** 2016-08-17 15:34 UTC
