### ISSUE TITLE
Click 4 router-links in turn, router-view can render all the pages first time, but click all the links again it router-view does not render.

### ISSUE THREAD

**Issue by kcmvp** [vuejs/vue-router#673] opened 2016-09-22 06:19 UTC
here is the source code to reproduce the issue

https://github.com/kcheng-mvp/jkf/tree/vue-route2

**Comment by posva** [comment] 2016-09-22 07:04
Can you provide that on a jsfiddle please? It is much easier for us to help that way

**Comment by kcmvp** [comment] 2016-09-22 07:14
Hi posva,

Thank your quick very much. I fact I am very new to vue/js and dont have experience with jsfiddle. I don't know how to transfer it to jsfiddle.

in order to reproduce the issue, you just need to checkout the source code and run 'npm run dev' .

be sure to on the branch 'vue-route2'

**Comment by kcmvp** [comment] 2016-09-22 07:19
![first_round](https://cloud.githubusercontent.com/assets/7655276/18739683/de564432-80d7-11e6-92e8-c7e76d8bc158.png)
![second_round](https://cloud.githubusercontent.com/assets/7655276/18739691/e5b74442-80d7-11e6-9d75-3abf1020bbe6.png)

**Comment by kcmvp** [comment] 2016-09-22 07:21
1: Click the links(4 link) one by one, for the first time, route-view (on the right) can render all the pages correctly.

2: after that click any link, you can find route-view does not render the page.

**Comment by LinusBorg** [comment] 2016-09-22 07:25
@posva a repro on fiddle won't be possible, he's using lazy-loading routes via webpack.

**Comment by kcmvp** [comment] 2016-09-22 14:23
Is it a bug? If yes, is there any walk around?

**Comment by LinusBorg** [comment] 2016-09-22 14:48
No idea, I'm at work and can't clone your repo here.

Please give us some time to actually look into it.

**Comment by kcmvp** [comment] 2016-09-22 14:51
@LinusBorg, 
Thank you very much! 
if you need I attache the source code, please speak out.

**Comment by LinusBorg** [comment] 2016-09-22 16:54
Okay so I checked out the repo. Very strange behaviour. 

I don't have an idea what's going on. My gut tells me maybe it has to dowith webpack 2-beta acting up?

**Comment by kcmvp** [comment] 2016-09-23 03:28
I had a post in webpack https://github.com/webpack/webpack/issues/3049

**Comment by fnlctrl** [comment] 2016-09-23 12:11
You're using vue-loader ^9.3 syntax of lazyloading (`resolve => require(['../modules/dashboard/index.vue'], resolve)`), while your installed version is 9.2. Please checkout vue-loader' [release notes](https://github.com/vuejs/vue-loader/releases).

You can either: 
1. Use System.import() since you're using webpack 2
2. Upgrade vue-loader to latest

**Comment by kcmvp** [comment] 2016-09-27 15:00
@fnlctrl 
Please see https://github.com/kcheng-mvp/jkf/tree/vue-route2, right now I am using the latest vue-loader. things goes even worse, it does not render the router-view even at the first time.

If I use import then it works well. you can find the code here
https://github.com/kcheng-mvp/jkf/tree/use-import

these two branch use the same package.json

**Comment by fnlctrl** [comment] 2016-09-27 16:28
@kcheng-mvp 
Try deleting vue-loader and installing it again.
If that didn't work, try using `System.import` because it normalizes module exports for you, if `vue-loader` somehow didn't.

**Comment by LinusBorg** [comment] 2016-09-27 16:41
@fnlctrl I just checked out the repo. it's loading the modules:

![bildschirmfoto 2016-09-27 um 18 40 47](https://cloud.githubusercontent.com/assets/1444526/18883029/f259b94c-84e1-11e6-939a-88008400eda7.png)

but not running/rendering them. no errors either. 

pretty weird.

**Comment by fnlctrl** [comment] 2016-09-27 16:46
@LinusBorg The modules are loaded, though not consumed by the router because of normalization issues (not resolving to `someModule.default` when `someModule` was `export default`-ed).

**Comment by fnlctrl** [comment] 2016-09-27 16:51
Forgot to add that this should be a vue-loader issue, since neither vue or vue-router handles that normalization logic..

**Comment by LinusBorg** [comment] 2016-09-27 16:54
Yeah I just tried with `System.import()` and that works ...

So we should close this here and open a ticket in the vue-loader repo ...

**Closed as completed by LinusBorg** 2016-09-27 16:54 UTC

**Comment by leaves4j** [comment] 2016-10-27 06:45
@LinusBorg Push a function which thrown an exception into global after guards,

``` js
router.afterEach(route => {
  throw new Error('There should throw an exception due to vue-router unknown bug');
});
```

Then it works well ... 
So I think maybe the issue caused by `vue-router`

**Comment by leaves4j** [comment] 2016-10-27 06:50
#841

**Comment by leaves4j** [comment] 2016-10-27 10:04
Is someone tracking the problem now?  I find that the issue was closed in webpack issues

**Comment by fnlctrl** [comment] 2016-10-27 15:35
It wasn't about webpack either. The problem could only be vue-loader
somehow not normalizing default export. Again, just use System.import as
you're using webpack 2.0.
