### ISSUE TITLE
$route.query in vue-router  can't be used in vue-resource as a param

### ISSUE THREAD

**Issue by hpaicf** [vuejs/vue-router#874] opened 2016-11-04 04:20 UTC
I use $route.query in vue-resource like this:

```javascript
Vue.http.get('/someUrl', {query: $route.query});
```
and receive an error:

****obj.hasOwnProperty** is not a function** 

I find in vue-route , it create query by using Object.create(null) and this is a completely blank object that doesn't inherit anything from Object. not any properties or  methods from Object. So it dosn't have hasOwnProperty method.

while i see in vue-resource, the 'each' function use obj.hasOwnProperty  to transform the query params.

so there is a conflect when i use $route.query as a param in vue-resource $http.get, that's definitely  an usual use in vue-router to get an url param object by $route.query.

maybe it can repalced by others like:
```javascript
 { } or Object.create(Object.prototype)
```

**Comment by fnlctrl** [comment] 2016-11-04 06:21
Closing as it's a duplicate of #873

**Closed as completed by fnlctrl** 2016-11-04 06:21 UTC
