### ISSUE TITLE
nested keep-alive and router-view render last route path component not current route component 

### ISSUE THREAD

**Issue by ctwowt** [vuejs/vue-router#3096] opened 2020-01-13 02:44 UTC
### Version
3.1.3

### Reproduction link
[https://codesandbox.io/s/peaceful-tdd-k2tvn](https://codesandbox.io/s/peaceful-tdd-k2tvn)

### Steps to reproduce
see gif or 
click buttons: 
Home -> a.aa.aaa -> Home -> a.aa.bbb 

### What is expected?
router-view working correctly

### What is actually happening?
router-view render last route component not current route path component  

---
https://github.com/vuejs/vue-router/blob/927f0c9013141c95df77a82b84acb7cc77c238c5/src/components/view.js#L35

But I Change code 

```js
if (vnodeData.keepAlive && parent._inactive) {
     inactive = true
}
```
to

```js
if (vnodeData.keepAlive) {
    inactive = parent._inactive
}
```

It's working.

![keep-alive-router-view-bug3](https://user-images.githubusercontent.com/37615488/72230539-2907f800-35f1-11ea-99d2-f6a0cf1921be.gif)

**Comment by posva** [comment] 2020-01-13 10:59
Duplicate of https://github.com/vuejs/vue-router/issues/2923
The opened PR does apply the same fix https://github.com/vuejs/vue-router/pull/2930
I will apply the changes and release them during the week

**Closed as completed by posva** 2020-01-13 10:59 UTC
