### ISSUE TITLE
Router Transition not updates DOM unless refreshed

### ISSUE THREAD

**Issue by Lahori-Jawan** [vuejs/vue-router#755] opened 2016-10-11 10:21 UTC
I am using vue 2.0.1 and router 2.0.0. I installed webpack template via cli following [**This link**](https://github.com/vuejs-templates/webpack). The problem is when I click a link, the view does not update or change but the address bar shows change in route. Then I refresh the page and DOM gets updated and hence shows the component as expected but again If I click to the previous link, same problem follows with same solution i.e. refresh.

Here is my setup!

// sidebar.vue

```
<template lang="html">
  <aside class="menu" style="padding:10px 0 0 15px;">

  <ul class="menu-list">
    <li><router-link to="/">Dashboard</a></li>
    <li><router-link to="/customers">Customers</router-link></li>
  </ul>
</aside>
</template>
```

//router.js

```
import Vue from 'vue'
import VueRouter from 'vue-router'

import Right from './Right'
import Customers from './Customers'


Vue.use(VueRouter)

const routes = [
  { path: '/', component: Right },
  { path: '/customers', component: Customers }
]
const router = new VueRouter({
  routes // short for routes: routes
})

export default router
```

// App.vue

```
<template>
  <div class="columns">

      <sidebar></sidebar>

      <router-view class="view"></router-view>

  </div>
</template>

<script>
import router from './components/router.js'
import Sidebar from './components/Sidebar.vue'

export default {
  router,
  components: {
    Sidebar
  }
}
</script>
```

// main.js

```
import Vue from 'vue'
import router from './components/router.js'

import App from './App'

new Vue({
  router,
  // el: '#app',
  render: h => h(App)
}).$mount('#app')
```

// index.html

```
<div id="app">
</div>
```

**Comment by fnlctrl** [comment] 2016-10-11 10:29
Hi, thanks for filling this issue. Please  follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live example on jsfiddle, codepen etc. Thanks!

**Comment by Lahori-Jawan** [comment] 2016-10-11 10:35
Thanks for your reply but I don't know if file with .vue extension is supported in jsfiddle.

**Comment by fnlctrl** [comment] 2016-10-11 10:47
You can use components' `template` option, with the standalone build of vue, so there's no need of `.vue` files.

**Comment by LinusBorg** [comment] 2016-10-11 11:11
...and if it's not reproducible on jsfiddle (please show!), then create a repository on github.

We work on this in your free-time, and setting up actual reproductions from some code snippets in an issue takes away a lot of our time, while you already possess the exact setup that leads to the problem.

**Comment by Lahori-Jawan** [comment] 2016-10-11 13:26
I created a repo of my project but when I download/clone (both) it and run 'npm run dev' it prompts an error, and I don't know why bec I am using the same project already. May be I am using `Vue` at two different locations. Because the error on cloned repo says 'Uncaught SyntaxError: Unexpected token import'. Can you direct me to a working repo with components? @LinusBorg

**Comment by Leonard1980** [comment] 2016-10-12 06:59
I experience the same problem. By the look of Lahori-Jawan's code, It might be the same as what I experince. Here is the code: 

https://github.com/Leonard1980/VueRouterTest

I don't know what is all about, but I'm guessing it might be a bug on not triggering the hashchange event. 

@LinusBorg I posted this also on the forum. Thanks.

**Comment by LinusBorg** [comment] 2016-10-12 17:33
@Leonard1980 I just tested your repo.

remove all those router imports and property assignments in App.vue and testPage.vue, and it works.
https://github.com/Leonard1980/VueRouterTest/blob/master/js/App.vue#L5
https://github.com/Leonard1980/VueRouterTest/blob/master/js/pages/testPage.vue#L6

Those are unnessassary and don't belong there.

I'm still curious as to _why_ this actually messes anything up, but it's not a bug IMHO

PS: you can access the router in any component via `this.$router`.

**Comment by LinusBorg** [comment] 2016-10-12 17:35
As this is the same error as in OPs post, I will close this now.

**Closed as completed** 2016-10-12 17:35 UTC
Labels: 2.x

**Comment by Leonard1980** [comment] 2016-10-13 07:38
@LinusBorg  Thanks! Now it works. 
I thought that this import and property assignment is necessary for the router to work. For example, in Vuex, the store property is necessary in the App component. I thought it goes the same with the router. Anyway, I'm glad that it finally works.
