### ISSUE TITLE
Make asynch code possible in RouteConfig.redirect functions

### ISSUE THREAD

**Issue by cartok** [vuejs/vue-router#3168] opened 2020-04-07 15:14 UTC
### What problem does this feature solve?
You might be required to execute async code in order to be able to make a decision on where to redirect to.  

**For example:**
1. Some external service generates a URI like */foo?value=value*
2. A user clicks on the link that came via email
3. The app should redirect from */foo* to */bar or /baz*. The decision on where to redirect to depends on another service (elastic for example). If it found data for *value=value* you want to redirect to */bar*. If not to */baz*. (could be a check if some product still exists where you want to let the user create a review for)

### What does the proposed API look like?
```javascript
// This redirect should execute properly
const route: RouteConfig = {
  path: '/foo',
  redirect: async function (to) {
    const info = await someApiRequest({ value: to.query.value })

    if (info) {
      return '/bar'
    } else {
      return '/baz'
    }
  }
}
```

**Comment by posva** [comment] 2020-04-07 15:16
Duplicate of https://github.com/vuejs/vue-router/issues/2729

**Closed as completed by posva** 2020-04-07 15:16 UTC
