### ISSUE TITLE
Replace is ignored by beforeRouteEnter

### ISSUE THREAD

**Issue by McPo** [vuejs/vue-router#3325] opened 2020-09-17 10:58 UTC
### Version
3.4.3

### Reproduction link
[https://jsfiddle.net/emcpoland/xb4kqLug/58/](https://jsfiddle.net/emcpoland/xb4kqLug/58/)

### Steps to reproduce
1. Click Items (The latest item id is "fetched from the server" and the user redirected to that items page)

2. Click delete (A dialog appears)

3. Click ok (The dialog is "dismissed" and the user is redirected to the next items page. Replace is used so that when the user clicks back, they don't see the dialog again [they would see the deleted item again, but in a real world situation it would say the item has been deleted])

It appears the fact that the navigation was meant to be a "replace" is dropped because of the navigation guard. Either "replace" should naturally be inherited or navigation guards should provide extra context and state that the navigation was meant to be a "replace". For now you can workaround this by passing `replace:true` in the props but its quite nasty IMO

### What is expected?
Pressing back after deleting an item should present with the previous item, not the previous item delete dialog.

### What is actually happening?
The delete dialog of the previous item is being shown. This is because despite the dialog using a `replace` navigation, this isnt carried over into the navigation guard. The guard also lacks context as to whether it should have been a replace or not.

**Comment by posva** [comment] 2020-09-17 11:16
Duplicate of https://github.com/vuejs/vue-router/issues/1620

**Closed as completed by posva** 2020-09-17 11:16 UTC
