### ISSUE TITLE
router-link active element needs to be matched only with url sensitive not query

### ISSUE THREAD

**Issue by HKskn** [vuejs/vue-router#2319] opened 2018-07-27 14:06 UTC
### What problem does this feature solve?
 I'm not sure is it bug or deliberately made. My problem is when I give an option to router-link as  `to="{path: '/audit', query: {year}}"`  and if application routed to '/audit/blabla'  then router-link element loses active class because of the query. If there is a different option to mark an element as active  by specified match type, we could easily manage the active link elements. Options may be 'url' or 'url query' even may be an array of strings. In this way we can handle much combinations.

### What does the proposed API look like?
```
// should match only path and query
<router-link :to={path: 'blabla', query: {'blalba': 'xxx'}} :match-type="['url', 'query']"> </router-link>

// should match only with url, It same as exact
<router-link :to={path: 'blabla', query: {'blalba': 'xxx'}} :match-type="['url']"> </router-link>
```

**Comment by posva** [comment] 2018-08-02 21:35
Duplicate of #2040

**Closed as completed by posva** 2018-08-02 21:35 UTC
