### ISSUE TITLE
Allow arbitrary mutable state within push()/replace()

### ISSUE THREAD

**Issue by J-Rojas** [vuejs/vue-router#3022] opened 2019-11-09 00:37 UTC
### What problem does this feature solve?
'Meta' allows for assigning immutable properties to a route. However there is a need to push arbitrary app state whenever a route changes to keep track of historical app state at the time of the route change. 'Meta' does not allow for the use of conditional state based on the route history. Currently the implementation uses the HTML5 history API for pushing state changes, but it does not allow the user to pass in arbitrary state that can be accessed again when going backwards in history. Please expose an extra parameter/object property to the API for this purpose.

### What does the proposed API look like?
Proposal:

```
$router.push({ name: 'my-route1', state: { foo: 'bar' } })
$route.state.foo // 'bar'
$router.go(-1)
$route.state.foo // undefined
```

**Comment by posva** [comment] 2019-11-09 14:23
Duplicate of https://github.com/vuejs/vue-router/issues/2243

**Closed as completed by posva** 2019-11-09 14:23 UTC
