### ISSUE TITLE
Prevent `$route` updating deactivated components when using keep-alive

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue-router#2739] opened 2019-04-24 13:56 UTC
### What problem does this feature solve?
When wrapping `router-view` inside `keep-alive`, the components which are kept alive, keep updating on every route change, if they depend on any `$route` properties like `$route.name` or `$route.params`.

This kinda defeats the purpose of keep-alive, because even though kept-alive components are not remounted, they update in every route change, even while they are deactivated.

### What does the proposed API look like?
The default behavior should be that $route only causes the component to update if the component has been activated.

**Comment by posva** [comment] 2019-04-24 18:08
Duplicate of https://github.com/vuejs/vue/issues/8819

**Closed as completed by posva** 2019-04-24 18:08 UTC

**Comment by franciscolourenco** [comment] 2019-04-24 20:20
Update:

There are a few practices which seem to prevent the component from updating when using vue-router:
1. Using component props instead of using `$route.params`, by setting `props:true` in the route definition.
2. Using the `router-link` component to implement button active states instead of comparing `$route` properties.

**Comment by franciscolourenco** [comment] 2019-04-24 20:22
So, router-link and route props are implemented in such a way which don't cause the component to update. Can't we do the same with the rest, ie. `$route`, `router-view`

**Comment by LinusBorg** [comment] 2019-04-24 21:31
You can always wrap the `<router-link>` in a normal component to isolate it from the parent's render cylce.

```javascript
const SolidRouterView = Vue.extend({
  render(h) {
    return h('router-view')
  }
})
```
