### ISSUE TITLE
Reserve optional dynamic parameters?

### ISSUE THREAD

**Issue by iGarym** [vuejs/vue-router#2617] opened 2019-02-20 03:19 UTC
### What problem does this feature solve?
repo: [jsfiddle](https://jsfiddle.net/zcgj5Lh4/)

When using `router-link` to navigate, the optional dynamic parameter `moduleId` is missing. In order to retain the parameters, we must manually provide the parameter or use router hooks. Non-optional parameters do not have this problem. Can we reserve the optional parameters when navigate?

******

使用 `router-link` 跳转时，可选的动态参数 `moduleId` 丢失了。为了保留参数，需要手动传参或者在路由钩子里处理。非可选的参数不会有这个问题，所以能否在跳转的时候保留可选的参数呢？

### What does the proposed API look like?
No new api.

**Comment by posva** [comment] 2019-02-22 13:37
Duplicate of #2110 
Or at least that's what it looks like.
Keep in mind params **must** be declared in the path url

**Closed as completed by posva** 2019-02-22 13:37 UTC
