### ISSUE TITLE
Docs on how to use vue-router with vue 2.7 composition api

### ISSUE THREAD

**Issue by mika76** [vuejs/vue-router#3764] opened 2022-07-19 07:30 UTC
### What problem does this feature solve?
I can't find anywhere info on how to use vue-router properly with the vue 2 version of composition api (especially now that 2.7 is out and people want to migrate slowly over). Which version of vue-router do I use - if I use 4.x the there is an unmet dependency on vue 3 - if I use 3.x then there are no composition api functions to use...

I know this might not be possible - but at the moment there is no info one way or the other, so really I'd just appreciate some clarification and suggest that maybe a comment in the docs would be helpful.

### What does the proposed API look like?
Add some docs

**Comment by posva** [comment] 2022-07-20 14:33
Duplicate of #3760

**Comment by posva** [comment] 2022-07-20 14:33
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed as not planned by posva** 2022-07-20 14:33 UTC
