### ISSUE TITLE
Type declaration incomplete for Location.query

### ISSUE THREAD

**Issue by mickeyzoox** [vuejs/vue-router#1932] opened 2017-12-08 20:25 UTC
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/82013/](https://jsfiddle.net/50wL7mdz/82013/) (This doesn't actually work, but shows the code you'd need locally to repro the bug)

### Steps to reproduce
0. Note that JSFiddle doesn't appear to give Typescript compiler errors, so the repro linked will have to be ported into a local Typescript Vue project.

1. In a Typescript Vue project:
```
router.push({ query: { array: ["1", "2", "3"] }})
```

### What is expected?
This should compile without error 

### What is actually happening?
You get an error:
```
 error TS2345: Argument of type '{ name: string; query: QueryParams; }' is not assignable to parameter of type 'RawLocation'.
  Type '{ name: string; query: QueryParams; }' is not assignable to type 'Location'.
    Types of property 'query' are incompatible.
      Type 'QueryParams' is not assignable to type 'Dictionary<string> | undefined'.
        Type 'QueryParams' is not assignable to type 'Dictionary<string>'.
          Index signatures are incompatible.
            Type 'string | string[] | undefined' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.
```

**Comment by posva** [comment] 2017-12-09 01:15
@ktsn I couldn't find anything about `Type 'string | string[] | undefined' is not assignable to type 'string'` but that line doesn't make sense to me. Do you know this error?

**Comment by ktsn** [comment] 2017-12-09 07:40
@posva No, I don't. In any cases, the snippet looks invalid as a repro since `query` won't accept `number[]` - the error should be `Type 'number[]' is not assignable to type 'string'.`
I suspect the error caused by the other place where `QueryParams` is used in OP's code.

**Comment by posva** [comment] 2017-12-11 10:12
It's weird I was getting the same output but I don't anymore 😆 
I was wondering if we should be more permissive about the query string because the user is able to provide custom query parsing (https://router.vuejs.org/en/api/options.html#parsequery--stringifyquery). I don't know if there's a smarter way to handle this though

**Comment by mickeyzoox** [comment] 2017-12-11 17:17
@ktsn @posva I have made 2 updates to the OP (I apologize the original bug report I posted was not completely correct):
-  I should have had `string`s in the repro not `number`s. The repro doesn't work in JSFiddle (I'm not sure why, I assumed that JSFiddle ignores Typescript compilation errors). Locally this expression fails to compile for me.
- The `vue-router` version I use locally is 2.7.0 (based on the source code annotation I don't think 3.0.1 fixes my problem though).

I think the line that would cause my problem is that the type declaration https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L110 is `query?: Dictionary<string>` when in fact `vue-router` also accepts query parameters that are `string[]` (this is true _even if the user doesn't specify custom query parsing_). This feature seems to be undocumented though.

You can verify that `vue-router` accepts for `query` values a `string[]` by visiting @posva 's JSFiddle at https://jsfiddle.net/posva/gnk3a044/1/ .

**Comment by zigomir** [comment] 2018-01-30 22:23
I have same issue, `string[]` works as expected but current typings won't let me use it.

**Comment by zigomir** [comment] 2018-02-07 17:55
This can be closed now with https://github.com/vuejs/vue-router/pull/2050 merged.

**Comment by posva** [comment] 2018-02-07 18:04
thanks, I didn't see I wasn't closed

**Closed as completed by posva** 2018-02-07 18:04 UTC

**Comment by MojoDeMedici** [comment] 2018-05-23 04:33
@posva @zigomir I am getting the same warning with params and named route.
It works, but in my IDE I get the annoying warning:

> Argument type {name:string, params:{"0":string, status:string, msg:string}} is not assignable to parameter type RawLocation.

Why? I mean why it works when compiled, but i get the warning message in my console?

**Comment by posva** [comment] 2018-05-23 11:12
It hasn't been released yet, it will be soon 🙂

**Comment by nicostuhlfauth** [comment] 2018-07-20 07:51
@posva Any updates? When will there be a new release?

**Comment by mika76** [comment] 2019-03-14 09:42
Getting this on vue-router 3.0.2...

**Comment by jordanboston** [comment] 2019-05-02 20:03
I'm wondering how to resolve this as well?  Any news?

**Comment by xyyVee** [comment] 2019-06-19 02:25
Since `query` should be `Dictionary<string>`,Here is my soluction and works fine for me:

```
private editArticel(id: string) {
    const otherQuery: Dictionary<string> = {}
    otherQuery.id = id
    this.$router.push({
      path: './editArticle',
      query: otherQuery
    })
  }
```

**Comment by m-shum** [comment] 2024-10-14 22:17
Has anyone figured this out? I keep getting `Type 'LocationQueryValue | LocationQueryValue[]' is not assignable to type 'string | string[] | undefined'.` when passing a computed value of a route query as a typed prop. Would be stellar to have some clear documentation on this.

in parent component:
```
const query = computed(() => useRoute().query.someKey)
```
in child component:
```
type TProps = {
query: string | string[] | undefined;
}
```
