### ISSUE TITLE
Allow rendering an alternate route without redirect

### ISSUE THREAD

**Issue by Goblinlordx** [vuejs/vue-router#2088] opened 2018-03-05 07:04 UTC
### What problem does this feature solve?
Given a few examples:

https://github.com/someProjectThatDoesntExist
https://github.com/goblinlordx/someRepoThatDoesntExist

When these pages render, you can see that even though these are "Not Found" the route doesn't change.  This (in my opinion) is fairly important for routing.  Fortunately, this is actually possible for certain cases.  For example:

```
{
  routes: [
    {path: "", component: "Index"},
    {path: "/settings", component: "Settings"},
    {path: "*", component: "NotFound"},
  ]
}
```

The above config will render the "NotFound" for routes such as `/doesntexist`.  For routes that are not dynamic, this is trivial to implement.  The problem comes when attempting to accomplish this same behavior when using navigation guards to determine if a path should be displayed to the user or not.  This could be because of failure to load data, or something like authorization.  The current examples do not actually accomplish this and instead actually change the path via redirection.

Currently, the navigation guard api only seems to support a few different actions that can be taken in response to a route being called.  These are:

 - Continue to the next route by calling `next()`
 - Fail to load the next route by never calling `next()` (probably not something that should be done)
 - Fail to load the next route by calling `next(false)`
 - Fail to load the next route by calling `next(<Error>)`
 - Redirect by pushing path `next({ path/name: "xxx")`
 - Redirect by replacing path `next({ path/name: "xxx", replace: true)`

None of these behave in a way similar to the Github example initially mentioned.

### What does the proposed API look like?
I would propose that when calling `next()` in a navigation guard (or possibly anywhere a `location` can be received) that there be an option that would allow the instance to be replaced without changing the URL.  This could be a property like `changeURL: Boolean (default false)`.  I am honestly not sure what the best name would be but it seems simple enough.  Another option might be something like calling next with something indicating it should behave as if it failed to match a route (not prevent matching another route).

**Comment by posva** [comment] 2018-03-05 08:22
Duplicate of #977

**Closed as completed by posva** 2018-03-05 08:22 UTC
