### ISSUE TITLE
selective abstract mode

### ISSUE THREAD

**Issue by zecar** [vuejs/vue-router#1977] opened 2018-01-09 16:48 UTC
### What problem does this feature solve?
this is my routes file
```js
var routes = [
        { path: '/members/logout', name: 'logout', component: Logout, meta: { pageTitle: 'Logout' } },
        { path: '/members/contact', name: 'contact', component: Contact, meta: {pageTitle: 'Contact'} },
        { path: '/', name: 'offline', component: LoggedOut, meta: {pageTitle: 'Logged Out'}, children: [
            { path: 'members/login', name: 'login' component: Authenticate, meta: {pageTitle: 'Authenticate'} },
            { path: 'members/signup', name: 'signup', component: Signup, meta: {pageTitle: 'Signup'} },
            { path: 'members/confirm', name: 'not-confirmed', component: NotConfirmed, meta: {pageTitle: 'NotConfirmed'} },
            { path: 'connect/callback', name: 'connect', component: Connect, meta: {pageTitle: 'Connect'} }
        ]}
]
```

Context: On initial load (or refresh) on the "/" route, inside the LoggedOut component I check a cookie that says the last viewed component (between Authenticate and Signup) and push that component to router.

It works ok, it redirects me to /members/login or /members/signup like it should. Now I want to make use of the "/" route as well. So if I open up the "/" route I want to see the correct component between Authenticate and Signup __**without**__ changing the URL. Only change the URL if I click navigational links inside the app. I only care for the initial load/refresh on the "/" route, after that I do not care.

Alias only works for one component

### What does the proposed API look like?
$router.push({name: 'Component', abstract: true})

OR

$router.replace({name: 'Component', abstract: true})

**Comment by LinusBorg** [comment] 2018-01-10 08:49
The simplest soplution is to simply make a Wrapper component for the `/`  route that conditionally displays the desired component.

I don't see a need for a new feature.

**Comment by zecar** [comment] 2018-01-10 09:20
Yes this popped in my head today also. But It should really be a feature because, in my opinion, I shouldn't have to add one extra component (even if it's basically just an if statement)

I'll implement this workaround for now but I still think this should be a feature.
 
I have different lifecycle hooks implemented in those two components and this workaround would mess things up, I'll have to add extra code to make this work

**Comment by LinusBorg** [comment] 2018-01-10 09:47
> But It should really be a feature because, in my opinion, I shouldn't have to add one extra component (even if it's basically just an if statement)

To put it a bit provocatively: That's basically saying "It should be a feature because I don't want to do a tiny bit of extra work for this one situation". That's not a good reason.

I understand that this feature would be useful in this example. But this example is a pretty limited use case for a very specific sitation that doesn't happen frequently (at least I haven't come across many people needing this so far), and it can be solved quite simply with the tools we already have.

So the usecase would have to be much broader, adding value for a wider ranger of situations and users, to justify that we add another feature with which have to maintain and test.

So I'm not *against* this feature categorically, but would requre additional use cases to consider it being "worthwhile".
  
>  I have different lifecycle hooks implemented in those two components and this workaround would mess things up, I'll have to add extra code to make this work

How so? Can you be more specific? The lifecycle hooks will run in either case, won't they?

**Comment by zecar** [comment] 2018-01-10 10:37
> How so? Can you be more specific? The lifecycle hooks will run in either case, won't they?

I started to type off my answer and it hit me. I only need one of the component to have its lifecycle hooks ran. After that it's just basic route change

I was gonna say that the lifecycle hooks will run just once for both of them because they are both created & mounted, right? If I wanted to keep only the root route I wouldn't be able to run the lifecycle hooks a second time. But I don't think I'd have to either.

So the only use case for this remains: If two or more components needs to be shown on the same route AND have the lifecycle hooks run every time a different component should be shown. Which doesn't sound much of a use case as it was initially.

I think I just became objective to my issue and don't think it should be a feature anymore. Thanks for making me think from another perspective.

this issue should be closed ?

**Comment by posva** [comment] 2018-01-10 10:48
Duplicate of #977

**Closed as completed by posva** 2018-01-10 10:48 UTC
Labels: feature request
