### ISSUE TITLE
Query parameters are rearranging on page load

### ISSUE THREAD

**Issue by mmeester** [vuejs/vue-router#3578] opened 2021-06-24 14:42 UTC
### Version
3.5.1

### Reproduction link
[https://test.groenkennisnet.nl/](https://test.groenkennisnet.nl/)

### Steps to reproduce
Run any project and paste the following query parameter on the end of the url in your browser:

`?q=tomaten&wq_flt=edu%2Fonderwijsniveau&wq_val=MBO&wq_flt=edu%2Fkwalificatiedossier%2Fomschrijving&wq_val=Dierhouderij en verzorging`

navigate to that page by pressing enter

look at the new url in the browser which is rearranged alphabetically to:
`?q=tomaten&wq_flt=edu%2Fonderwijsniveau&wq_flt=edu%2Fkwalificatiedossier%2Fomschrijving&wq_val=MBO&wq_val=Dierhouderij%20en%20verzorging`

### What is expected?
- the query parameters should stay in the same order

### What is actually happening?
- query parameters are rearranged

**Comment by posva** [comment] 2021-06-24 16:22
Duplicate of #3447

**Closed as completed by posva** 2021-06-24 16:22 UTC
