### ISSUE TITLE
Pinterest / Producthunt like modal navigation

### ISSUE THREAD

**Issue by Nekudapsik** [vuejs/vue-router#823] opened 2016-10-23 12:51 UTC
Is there any way to achieve Pinterest or Producthunt like modal navigation?

I mean, whichever page you are on, when you click on a item a modal with the item details pops up, and the page (feed) where you are from still sits in the background. The url in the address bar changes so you can link to the item from other sites or share it to your friends. And when you close the item modal your still at the feed.

Does vue-router support this type of routing?

**Comment by simplesmiler** [comment] 2016-10-23 13:45
Appears to be duplicate of https://github.com/vuejs/vue-router/issues/703

**Closed as completed by simplesmiler** 2016-10-23 13:45 UTC
