### ISSUE TITLE
Suggestion. Several components in config.

### ISSUE THREAD

**Issue by LuckyBlade** [vuejs/vue-router#262] opened 2015-12-02 06:10 UTC
Hello. I'm using vue-router and now it's working like this:
```
    router.map({
      "":{
        component: comp1,
        subRoutes: {
          "/path1":{
             component: comp3,
             subRoutes:{}
          }
        }
      }
     }); 
```
But  need something like this:
```
    router.map({
      "": [{
        component: comp1,
        subRoutes: {
          "/path1":[{
             component: comp3,
             subRoutes:{}
          }],
         "/path2":[{
            component: comp4,
            subRoutes:{}
          }]
        }
      },{
        component : comp2,
        subRoutes : {
          "/path1":[{
             component: comp5,
             subRoutes:{}
         }],
          "/path2":[{
             component: comp6,
             subRoutes:{}
          }]
        }
       }]
    }); 
```
In other words it needs router to return on one route more than one component with its subroutes( may be different ). Now I need to create accessory Vue components just for contain main components. But sometimes it doesn't help and I need to create additional router(s). Please look at picture.
![2015-12-02 12-01-04](https://cloud.githubusercontent.com/assets/15211756/11523512/0afd641c-98ed-11e5-8492-11dfeda1ac03.png)

I don't think that several routers is good idea. In any case, I could be wrong and do something wrong. I would be grateful if you tell me where I'm wrong.

**Comment by yyx990803** [comment] 2015-12-02 14:37
Duplicate of #213

**Closed by yyx990803** 2015-12-02 14:37 UTC
