### ISSUE TITLE
active-class is not given to named routes if the URL does not include the trailing slash /

### ISSUE THREAD

**Issue by theshem** [vuejs/vue-router#826] opened 2016-10-24 15:50 UTC
Consider the following snippet:

``` html
<router-link :to="{name: 'home'}" exact>Home</router-link>
<router-link to="/user">/user (2) </router-link>
<router-link :to="{name: 'user'}">user (named route) (3) </router-link>

<router-view></router-view>
```

``` js
const router = new VueRouter({
  mode: 'history',
  routes: [
    { 
      path: '/user', 
      component: User,
      children: [
        { 
          path: '',
          name: 'user',
          component: UserHome 
        }
      ]
    },
    {
      path: '',
      name: 'home',
      component: Home,
    }
  ]
});
```

**[Example here](http://jsbin.com/rivapah/2)** -  click on the link (2), then click on the `Home` and finally click on the link (3).

Notice that the link (2) and link (3) are 'exact' same routes. But they both don't get the `active-class` at the same time if you click on the link (2).

However the `active-class` is added to both of them by clicking on the link (3).

That is because of the trailing slash `/` on the (3) link I guess.

**Comment by theshem** [comment] 2016-11-08 13:54
Any update on this?

**Comment by LinusBorg** [comment] 2016-11-08 13:57
No, unfortunately.

**Comment by morficus** [comment] 2016-11-08 22:12
I have the same issue but a different use case:

I have 2 routes:

``` JS
const router = new VueRouter({
    mode: 'history', 
    root: '/',
    routes: [
        {
            path: '/user',
            component: UserList,
            name: 'user.list'
        }, {
            path: '/user-models',
            component: UserModelsList,
            name: 'user-models.list'
        }
    ]
});
```

And this in my component:

``` HTML
<router-link :to="{path: '/user'}">User</router-link>
<router-link :to="{path: '/items'}">Other Items</router-link>
<router-link :to="{path: '/user-models'}">User Models</router-link>
```

And this is the result:

![screen shot 2016-11-08 at 5 14 27 pm](https://cloud.githubusercontent.com/assets/718799/20119531/dc95cc16-a5d6-11e6-892c-278798526874.png)

^ as you can see... both `router-link` elements are marked as active even tho is should only be matching one of them.

**Comment by theshem** [comment] 2016-11-09 11:26
@morficus That is a different issue. I guess the `exact` property is what you are looking for:

Check out the `exact` property in [vue-router doc](https://router.vuejs.org/en/api/router-link.html).

For instance:

``` html
<router-link :to="{path: '/user'}" exact>User</router-link>
<router-link :to="{path: '/items'}" exact>Other Items</router-link>
<router-link :to="{path: '/user-models'}" exact>User Models</router-link>
```

**Comment by LinusBorg** [comment] 2016-11-09 11:43
@HashemQolami well, @morficus has a point.

It you want use `exact false` to highlight a route including all subroutes, and ad the same time have a sibling route whose path starts with the same string (as above: `/user` and `/user-items`), that sibling would incorrectly be highlighted as well.

@morficus But it _is_ indeed a seperate problem, please open a separate issue.

**Comment by morficus** [comment] 2016-11-09 20:09
@LinusBorg and @HashemQolami - I'll open a new issue

But (at least for now) my "work around" is to change the `path` attribute on my `router-link` elements from `/user` to `/user/` and it solved the highlighting problem.

Tho I do see why you would rather treat this is a different issue (because the root cause is not the same).

**Closed as completed** 2016-11-13 02:04 UTC
Labels: bug, 2.x
