### ISSUE TITLE
Lazy Loading and  fastClick

### ISSUE THREAD

**Issue by CARVIN94** [vuejs/vue-router#1016] opened 2016-12-14 04:03 UTC
I use Lazy Loading like this in vue2: 
const Foo = resolve => require(['./Foo.vue'], resolve)
it can not work in the the second time click,

and please teach me how to fastclick (remove touch 300ms)  in vue2, think.

**Comment by CARVIN94** [comment] 2016-12-14 07:07
and in mode: 'history' some time will be refresh ....

**Comment by simplesmiler** [comment] 2016-12-14 07:49
Hello!

Regarding the issue with component resolving, please provide a reproduction repo, because otherwise we can not triage the issue.

Regarding usage questions, we encourage you to ask them on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to keep the issue tracker for bug reports and feature requests.

**Comment by fnlctrl** [comment] 2016-12-14 10:50
> it can not work in the the second time click,

It's a known issue only seen with webpack 2.0 + require. Please use `System.import` instead. More explanation: https://github.com/vuejs/vue-router/pull/862

**Closed as completed by fnlctrl** 2016-12-14 10:50 UTC
Labels: need repro
