### ISSUE TITLE
<router-link> broken with Vue <2.6.9 and vue-router >3.0.7

### ISSUE THREAD

**Issue by mattmink** [vuejs/vue-router#3028] opened 2019-11-11 20:26 UTC
### Version
3.1.3

### Reproduction link
[https://codepen.io/matthewjmink/pen/yLLqQyX?editors=1010](https://codepen.io/matthewjmink/pen/yLLqQyX?editors=1010)

### Steps to reproduce
* install Vue 2.6.8
* install vue-router 3.1.3
* setup routes and base config
* add router-view and router-link elements to the app
* observe that <router-link> elements are not links

### What is expected?
<router-link> becomes an anchor tag

### What is actually happening?
Only the text for the default slot is output.

**Comment by posva** [comment] 2019-11-11 20:28
Duplicate of https://github.com/vuejs/vue-router/issues/3016

**Comment by mattmink** [comment] 2019-11-11 20:28
Ah, sorry for the duplicate, @posva. I searched for the issue but didn't find it. Thanks for the link.

**Closed as completed by posva** 2019-11-11 20:28 UTC
