### ISSUE TITLE
Optional Route Params & Child Route Issue

### ISSUE THREAD

**Issue by AkiraLaine** [vuejs/vue-router#1294] opened 2017-03-31 05:08 UTC
Hey,

There seems to be an issue with using optional route parameters and child routes. For example, lets say I have the following:
```
const router = new VueRouter({
  mode: 'history',
  routes: [
    {
        path: '/blog/:blogPostId/:blogPostSEO?',
        component: blogPostShell,
        children: [
            {
                path: '',
                name: 'blogpost',
                component: blogPostContent
            },
            {
                path: 'comments',
                name: 'blogpost-comments',
                component: blogPostComments
            }
        ]
    } 
  ]
});
```
Given that `:blogPostSEO` is an optional param, if I go to `http://localhost:8080/blog/1/how-to-make-coffee/comments`, then the `blogPostComments` component properly renders. But if I go to `http://localhost:8080/blog/1/comments`, then instead of rendering `blogPostComments` it will render the `blogPostContent` component.

If I had more child routes and went to `/blog/:blogPostId/childRoute`, then it will always render the `blogPostContent` component instead of the childRoute component.

I know this is a contrived example, but I hope I explained the issue properly.

Versions:
```
Vue 2.2.1
Vue-Router: 2.3.0
```

**Comment by Sinboo** [comment] 2017-03-31 15:30
Yes, same for me, hope fix it

**Comment by javoski** [comment] 2017-03-31 16:41
IMO this is expected according to your routes configuration. 
To meet your expectation, you may modify your config to this:
```js
const router = new VueRouter({
  mode: 'history',
  routes: [
    {
        path: '/blog/:blogPostId/:blogPostSEO?',
        component: blogPostShell,
        children: [
            {
                path: 'comments',
                name: 'blogpost-comments',
                component: blogPostComments
            },
            {
                path: '',
                name: 'blogpost',
                component: blogPostContent
            }        
        ]
    } 
  ]
});
```
Put comments child route before the default one.

**Comment by AkiraLaine** [comment] 2017-03-31 23:33
@xujiongbo Does that work? I'll try it out later. But tbh, if the parameter isn't specified, it should work as if  the path was specified as follows: ` path: '/blog/:blogPostId'`

**Comment by posva** [comment] 2017-04-01 11:12
The problem with your approach is that the regex generated by the path with the optional param will match in cases you don't want to match: `/blog/1/comments` matches `/blog/:blogPostId/:blogPostSEO?` and therefore renders the first child route. I'd personally use some kind of redirect, alias or append the seo part at the end or simply not making it optional.
So as @xujiongbo said, I also think it's an expected behaviour
WDYT @fnlctrl ?

**Comment by AkiraLaine** [comment] 2017-04-02 00:09
@posva It still feels a bit weird, it's an optional param, if I don't include it then vue-router should find a way to check if i'm targeting a child route or something.

But I do see what you're saying.

**Comment by posva** [comment] 2017-04-04 08:46
Closing since the problem lies within the regex generated by the path. You can also add a static part to the path: `path: '/blog/:blogPostId/seo-:blogPostSEO?'`

**Closed as completed by posva** 2017-04-04 08:46 UTC

**Comment by AkiraLaine** [comment] 2017-04-06 01:41
Just to let you know that @xjchengo's solution fixed the issue 😄
