### ISSUE TITLE
Wrong component being rendered when nested 3 deep with both <keep-alive> and <transition>

### ISSUE THREAD

**Issue by jordi735** [vuejs/vue-router#3365] opened 2020-11-05 13:17 UTC
### Version
3.4.8

### Reproduction link
[https://jsfiddle.net/3q97L50m/](https://jsfiddle.net/3q97L50m/)

### Steps to reproduce
If you nest a route 3 deep. With the one on the second and third level wrapped in both a `<keep-alive>` and `<transition>`. The wrong component renders when switching from level 2 if that makes sense.

### What is expected?
The router should load whichever component is defined in the routes array.

### What is actually happening?
When you click on the deepest nested component, the one loaded previously always shows instead of the one the `<router-link>` points to.

---
I'm having a hard time explaining by typing. I really hope my fiddle shows it properly. (https://jsfiddle.net/3q97L50m/)

**Comment by posva** [comment] 2020-11-05 14:11
Duplicate of #1242 

Use `<router-view :key="$route.path"/>` to ensure a different router-view instance is used

**Closed as completed by posva** 2020-11-05 14:11 UTC

**Comment by jordi735** [comment] 2020-11-05 14:59
That creates a new instance for every route I visit. Meaning it runs `created()` everytime and (in my case) does http calls when I switch routes: [https://imgur.com/a/rpDwGhK](https://imgur.com/a/rpDwGhK) (there should be only 1 instance of Moods)

If I throw the `:key` on the first level component it causes the entire the second level child to be rerendered when switching third level childs inside the second level child. :(
