### ISSUE TITLE
Route alias does not set active link class

### ISSUE THREAD

**Issue by nolimitdev** [vuejs/vue-router#2340] opened 2018-08-06 15:06 UTC
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/8xrk1n9f/1279/](https://jsfiddle.net/8xrk1n9f/1279/)

### Steps to reproduce
Clicking at alias does not set active link class for router link referencing to About component. I think users expect this active class to work because router-link knows route definition and de facto it's alias(es). By vue-router doc aliases should behave the same way as origin route. So it should be fixed/implemented or add explicit note to <a href="https://router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect">https://router.vuejs.org/guide/essentials/redirect-and-alias.html#alias</a> and/or <a href="https://router.vuejs.org/api/#active-class">https://router.vuejs.org/api/#active-class</a> that active class does not work with aliases.

### What is expected?
Active class should be set

### What is actually happening?
Active class is not set

**Comment by posva** [comment] 2018-08-06 16:26
Duplicate of #419

**Closed as completed by posva** 2018-08-06 16:26 UTC
