### ISSUE TITLE
v-if mutating router-link to

### ISSUE THREAD

**Issue by byalexandrepedrosa** [vuejs/vue-router#2603] opened 2019-01-31 15:32 UTC
### Version
3.0.2

### Reproduction link
[https://gist.github.com/WisdomEye/d5b8169550ac06c3062490e51061a1e8](https://gist.github.com/WisdomEye/d5b8169550ac06c3062490e51061a1e8)

### Steps to reproduce
Just add an li using v-if, and then try change the value of variable, in the example bellow update start with value 0, I can add a button to increment or decrement it, and get error about mutating :for from router-link.

	<li v-if="update" id="dashboard-menu-top-updates">
		<router-link :to="{ name: 'Update' }" :exact="$route.name === 'Update'">Atualizações</router-link>
	</li>

### What is expected?
The expected is render or remove the element without errors about mutating ":to" from router-link

### What is actually happening?
The li is correctly rendered as wished, but make a lot of erros on console about mutating ":to" from router-link.

Error:

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "to"

**Comment by posva** [comment] 2019-01-31 15:34
Hey, a runnable repro is necessary, you can fork this: https://jsfiddle.net/posva/9r6xhqbp/
Closing until one is provided

**Closed as completed by posva** 2019-01-31 15:34 UTC

**Comment by WisdomEye** [comment] 2019-01-31 17:09
After make the repo for replicate the issue, have found it is not a problem with vue-router, since worked like desired on jsfiddle.

[https://jsfiddle.net/WisdomEye/8uabg9so/](https://jsfiddle.net/WisdomEye/8uabg9so/)

Since I am using SSR with Laravel as API and the package:

[https://github.com/spatie/laravel-server-side-rendering/issues](https://github.com/spatie/laravel-server-side-rendering/issues)

My guess, the problem is how the spatie/laravel-server-side-rendering pack the contents.

**Comment by byalexandrepedrosa** [comment] 2019-01-31 17:09
After make the repo for replicate the issue, have found it is not a problem with vue-router, since worked like desired on jsfiddle.

[https://jsfiddle.net/WisdomEye/8uabg9so/](https://jsfiddle.net/WisdomEye/8uabg9so/)

Since I am using SSR with Laravel as API and the package:

[https://github.com/spatie/laravel-server-side-rendering/issues](https://github.com/spatie/laravel-server-side-rendering/issues)

My guess, the problem is how the spatie/laravel-server-side-rendering pack the contents.
