### ISSUE TITLE
`router-link` doesn't react where route changes

### ISSUE THREAD

**Issue by imcvampire** [vuejs/vue-router#876] opened 2016-11-04 07:12 UTC
When I pass a `tag` prop to `<router-link>`, it doesn't reaction when `to` param changes:
```
<router-link role="presentation" :to="{ name: 'profileBlog', params: { profileName: $route.params.profileName } }" tag="li">
   <a>
    <span class="glyphicon glyphicon-picture"></span> Blog
  </a>
</router-link>
``` 

But this code works fine:
```
<li>
  <router-link :to="{ name: 'profileBlog', params: { profileName: $route.params.profileName } }">
    Blog
  </router-link>
</li>
```

**Comment by fnlctrl** [comment] 2016-11-04 07:16
Hi, thanks for filling this issue, closing as it's a duplicate of #810.

**Closed as completed by fnlctrl** 2016-11-04 07:16 UTC
