### ISSUE TITLE
Default route inside children doesn't work

### ISSUE THREAD

**Issue by strexicious** [vuejs/vue-router#1553] opened 2017-06-30 23:19 UTC
### Version
2.7.0

### Reproduction link
[http://jsfiddle.net/ugfcccur/](http://jsfiddle.net/ugfcccur/)

### Steps to reproduce
Only Step: Click the '/user/foo/nopudont' path

### What is expected?
Redirects to '/user/foo/' loading 'UserHome' component

### What is actually happening?
Navigates to '/user/foo/nopudont' not redirecting, and not loading any component

---
Creating a SPA using vue-cli webpack template with webpack-dev-server.

**Comment by LinusBorg** [comment] 2017-06-30 23:54
Redirects have to be a full path - if you choose to use a path. in this instance, it's better to use a name:

https://jsfiddle.net/ugfcccur/1/

This is not a bug but a conceptual limitation that can be easily avoided with named routes, so I'm closing this.

**Closed as completed by LinusBorg** 2017-06-30 23:54 UTC
