### ISSUE TITLE
redirect to alias, the active-class doesn't work

### ISSUE THREAD

**Issue by lmh2072005** [vuejs/vue-router#1009] opened 2016-12-12 08:42 UTC
### Vue.js / vue-router versions
2.1.2 / 2.1.1

### What is actually happening?

when i redirected to '/index' , the active-class is right ; 
````html
<router-link tag="li" active-class="current" to="/index">
        <a title="home" href="javascript:;" >home</a>
</router-link>
````
i seted the alias , when i redirected to '/' ,the active-class doesn't work
````javascript
{
      path : '/index',  
      alias : '/',
      component : test
}
````

**Comment by posva** [comment] 2016-12-12 09:14
Please provide a jsfiddle. I couldn't reproduce: https://jsfiddle.net/posva/omt23qs1/

**Comment by lmh2072005** [comment] 2016-12-13 10:05
@posva   https://jsfiddle.net/lmh2072005/Lxx6hnaz/   ，when i changed the router , the alias router still has the class 'router-link-active'

**Comment by lmh2072005** [comment] 2016-12-13 10:34
````html
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <style>
        .router-link-active{
            color:#ff3300;
        }
    </style>
</head>
<body>
<div id="app">
    <router-link to="/index">/home</router-link>
    <router-link to="/foo">/foo</router-link>
    <router-view></router-view>
</div>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
<script>
    const Home = { template: '<div>Home</div>' }
    const Foo = { template: '<div>Foo</div>' }

    const router = new VueRouter({
        routes: [
            { path: '/index', alias : '/', component: Home },
            { path: '/foo', component: Foo }
        ]
    })
    new Vue({
        router,
        el: '#app'
    })

</script>
</body>
</html>
````
the second problem ：
i saved the code above as index.html,
i input the url 'http://localhost:8080/index.html#/index' to the browser, the active-class is ok ,but when i input the url 'http://localhost:8080/index.html#/' to the browser ,the active-class doesn't work.

**Comment by LinusBorg** [comment] 2016-12-13 10:40
That's because the path for the active class is not matched exactly be default.

`/foo` starts with `/`, so it matches.

To change this behaviour to use an exact match only, use `<router-link to="/" exact>`

https://router.vuejs.org/en/api/router-link.html

I will close this as it's not a bug as far as I can tell. If you disagree, please comment and we can reopen.

For further support with "how to", use forum.vuejs.org

**Closed as completed by LinusBorg** 2016-12-13 10:40 UTC
Labels: need repro

**Comment by lmh2072005** [comment] 2016-12-13 12:09
@LinusBorg  what should i do with the second problem ?

**Comment by LinusBorg** [comment] 2016-12-13 12:17
> For further support with "how to", use forum.vuejs.org

**Comment by nolimitdev** [comment] 2018-08-06 15:16
It is not "how to" but bug or feature request. It seems that active class and aliases does not work together at all. See this: https://github.com/vuejs/vue-router/issues/2340
