### ISSUE TITLE
Export RouterLink component

### ISSUE THREAD

**Issue by sebamarynissen** [vuejs/vue-router#3466] opened 2021-02-01 14:30 UTC
### What problem does this feature solve?
I have a use case where I want to implement a custom `<nav-link>` component that builds on top of `<router-link>`. While this is perfectly possible, it requires me to replace all my `<router-link>` references with `<nav-link>` (and I have about 200 of them). Therefore it would be useful to be able to explicitly reference Vue Router's `<router-link>` in the `<nav-link>` component so that I can globally register my component as
```js
import Vue from 'vue';
import Router from 'vue-router';
import NavLink from './nav-link.vue';

Vue.install(Router);
Vue.component('router-link', NavLink);
```

### What does the proposed API look like?
I propose to explicitly export the `<router-link>` component (and perhaps `<router-view>` as well) so it can be imported like this:
```vue
// # nav-link.vue
<template>
  <router-link>
    <slot></slot>
  </router-link>
</template>

<script>
import { RouterLink } from 'vue-router';

export default {
  components: {
    RouterLink,
  },
};
</script>
```

I will file a PR for this.

**Comment by posva** [comment] 2021-02-01 14:31
Duplicate of https://github.com/vuejs/vue-router/issues/1976

**Closed as completed by posva** 2021-02-01 14:31 UTC

**Comment by sebamarynissen** [comment] 2021-02-01 14:40
My apologies.
