### ISSUE TITLE
beforeEach doesn't trigger on full page reload

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue-router#748] opened 2016-10-09 11:11 UTC

**Comment by yyx990803** [comment] 2016-10-09 20:06
Cannot reproduce, please provide a reproduction.

**Comment by rightaway** [comment] 2016-10-10 07:04
```
const router = new VueRouter({
  routes: [
    { path: '/home', component: Home }
  ]
})

new Vue({
  router
}).$mount('#app')

router.beforeEach((to, from, next) => {
  console.log('beforeEach')
  return next();
});
```

`beforeEach` doesn't get printed if you do a browser refresh (pressing F5), but it does if you navigate between pages via a `router-link`.

**Comment by LinusBorg** [comment] 2016-10-10 07:41
Still can't reproduce, works for me: http://jsfiddle.net/Linusborg/mnqnwcfr/

**Comment by LinusBorg** [comment] 2016-10-13 06:46
Closing this as In can't reproduce this and OP didn't provide a reproduction.

We will re-visit the issue if a reproduction can be provided.

**Closed as completed by LinusBorg** 2016-10-13 06:46 UTC
Labels: need repro

**Comment by lepture** [comment] 2016-12-20 04:24
@yyx990803 @LinusBorg 

Look at the code that @rightaway provided.

```
router.beforeEach((to, from, next) => {
  console.log('beforeEach')
  return next();
});
```

The above code is located below the mount of Vue app. If we move the `beforeEach` code above of the `app.$mount`, it would print `beforeEach` message.

**Comment by fnlctrl** [comment] 2016-12-20 07:39
@lepture That's expected behavior. Since you registered `beforeEach` after $mount-ing vue, when vue $mounts, the router doesn't have a beforeEach hook yet, so it won't be called on initial load.

**Comment by lepture** [comment] 2016-12-20 08:51
@fnlctrl I was explaining how to reproduce @rightaway bug to @yyx990803 and @LinusBorg.

**Comment by Erigers** [comment] 2017-06-05 13:29
the exact same thing is happening to me. This is what I do:
```
beforeRouteEnter (to, from, next) {
      console.log('in beforerouteenter');
      profileService.getProfile((response) => {
        store.state.tempProfile = response.data;
        console.log('got data');
        console.log(store.state.tempProfile);
        return next();
      });
    },
```
It prints all console.logs but still redirects me on my home page. This happens when I reload the page, but not when I navigate in-app.

I am following this page on router docs: https://router.vuejs.org/en/advanced/data-fetching.html

This line: 
```
 next(vm => vm.setData(err, post))
```
is throwing an error as well, 
**Edit**
I managed to fix the first part, there is nothing wrong with the guard 💯 
Second part as well

**Comment by sunceenjoy** [comment] 2018-04-06 16:05
You should call router.beforeEach before Vue.use(router).
https://forum.vuejs.org/t/router-beforeeach-if-manually-input-adress-in-browser-it-does-not-work/12461/3

**Comment by caomengsi** [comment] 2018-11-11 12:14
good answers

**Comment by jitendra1607** [comment] 2019-04-23 11:27
> https://forum.vuejs.org/t/router-beforeeach-if-manually-input-adress-in-browser-it-does-not-work/12461/3



> You should call router.beforeEach before Vue.use(router).
> https://forum.vuejs.org/t/router-beforeeach-if-manually-input-adress-in-browser-it-does-not-work/12461/3

if Vue router is used in 'abstract' mode then router.beforeEach not getting called on page reload.

**Comment by pancerZH** [comment] 2019-05-27 02:06
> You should call router.beforeEach before Vue.use(router).
> https://forum.vuejs.org/t/router-beforeeach-if-manually-input-adress-in-browser-it-does-not-work/12461/3

could not be better

**Comment by spongege** [comment] 2019-09-25 02:15
卧槽还真的踩了这个坑。。。总算解决了

**Comment by gustavorps** [comment] 2022-02-02 22:51
What is `vm`?
