### ISSUE TITLE
Asking if user wants to leave page causes vue-router to not handle navigation properly

### ISSUE THREAD

**Issue by lbosquett** [vuejs/vue-router#3900] opened 2024-08-20 18:01 UTC
### Version
3.6.5

### Reproduction link
[github.com](https://github.com/lbosquett/vue-router-2-bug-reproduction)

### Steps to reproduce
1.launch the application and open a new page with the initial app page (https://github.com/lbosquett/vue-router-2-bug-reproduction)
2. click on page 2
3. click on page 3
4. click on the button to enable the navigation guard, this will ask the user to navigate back and forward with a `confirm` dialog
5. on page 3, click to navigate backwards (browser arrow to go to previous page)
6. the dialog will appear, click on "cancel"
7. try to navigate to the previous page

the behavior can be different if you opened the app through a new page or about:blank, or if you just opened the application (being the very first page)

### What is expected?
the navigation guard should run consistently and the history must be preserved on browser whatever the user clicks on ok or cancel the navigation.

### if you opened this application through a new page or about:blank page:
notice the previous and next page arrows won't work until the user interact with page, and if you interact with the page and then go to the previous page browser will move you to the very first page (about:blank or new tab) without respecting the history order

### if you have cleared history and the very first page you have in the application is actually the application first page:
then the browser will move you to without respecting the navigation guard, until you interact with the page

---
videos explaining it: https://github.com/lbosquett/vue-router-2-bug-reproduction/tree/main/videos

this is working fine on vue router 4.x for vue 3. I tested the versions 3.2.0 and 3.6.5 (latest until Aug, 20)

it seems it have something to do with history event handling, we noticed that browsers added support for the popstate and this may be the breaking change between vue router for vue 2 and vue 3.

repositories:
vue 2 with bug: https://github.com/lbosquett/vue-router-2-bug-reproduction
vue 3 working: https://github.com/lbosquett/vue-3-vue-router-working

**Comment by posva** [comment] 2024-08-21 08:35
I think this is a duplicate of #2573

**Closed as not planned by posva** 2024-08-21 08:35 UTC
