### ISSUE TITLE
[Docs] Changed to Vuepress?

### ISSUE THREAD

**Issue by brunokunace** [vuejs/vue-router#2220] opened 2018-05-25 14:51 UTC
### Version
3.0.1

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
check on mobile or any small screen and click to hamburger menu

### What is expected?
Open menu and results of search bar

### What is actually happening?
link of menu dont work (dont make anything). Same as search input

---
VuePress is awesome, please fix it!!

**Comment by ulivz** [comment] 2018-05-25 15:06
Duplicate of https://github.com/vuejs/vuepress/issues/492.

**Comment by posva** [comment] 2018-05-25 15:06
That's a vuepress issue and I think there's already an issue opened

**Closed as completed** 2018-05-25 15:06 UTC
