### ISSUE TITLE
Router-link by name ":to-name"

### ISSUE THREAD

**Issue by de-don** [vuejs/vue-router#2998] opened 2019-10-17 06:12 UTC
### What problem does this feature solve?
It would be convenient to have a shortcode for routing by name of the route. This will save the user from constantly passing an object with only one "name" field

### What does the proposed API look like?
I propose to create a shortcut:
```vue
<router-link to-name="home"> Home page </router-link>
```
that will be equal to
```vue
<router-link :to="{name: 'home'}"> Home page </router-link>
```

**Comment by posva** [comment] 2019-10-17 07:02
Duplicate of https://github.com/vuejs/vue-router/issues/2818

**Closed as completed by posva** 2019-10-17 07:02 UTC
