### ISSUE TITLE
Nested routes with keep-alive creates child on hidden branch

### ISSUE THREAD

**Issue by davidmoser** [vuejs/vue-router#3195] opened 2020-05-11 18:00 UTC
### Version
3.1.6

### Reproduction link
[https://jsfiddle.net/7v8hje5d/8/](https://jsfiddle.net/7v8hje5d/8/)

### Steps to reproduce
- Open console
- Click on link /A/1
- Click on link /B/1

### What is expected?
- First click creates child with parent A
- Second click creates child with parent B

### What is actually happening?
- First click works as expected
- Second click creates two children, one with parent A and one with parent B

---
I used a key in the router view to make sure children with the same parent get cached independently:
:key="$route.fullPath"

The setup works correctly if the router views have no keys and different child component types.

**Comment by posva** [comment] 2020-08-03 09:26
Duplicate of https://github.com/vuejs/vue/issues/8819

**Closed as completed by posva** 2020-08-03 09:26 UTC
