### ISSUE TITLE
Different route define, but the same suffix path, will all be actived!

### ISSUE THREAD

**Issue by muei** [vuejs/vue-router#1091] opened 2017-01-11 10:11 UTC
`vue-router`'s version:  *3.10.9*
```
// routes.js
const routes = [
   {name: 'tag', path:'tag'},
   {name: 'tagtype', path:'tagtype'}
]

// pug's template
ul
   li(v-for="item in items")
      router-link(active-class="active" v-bind:to="item.to") 

// data
[
  {title: 'tagtype',  to: {name: 'tagtype'}},
  {title: 'tag', to: {name: 'tag'}},
]
```
The url path `/tag` '/tagype' will all be actived!
If change `tagtype` with a different suffix, like `atagtype`, this bug will be fixed!

**Comment by posva** [comment] 2017-01-11 10:13
This is expected, you're looking for the `exact` prop on router-link: https://router.vuejs.org/en/api/router-link.html#exact

**Comment by muei** [comment] 2017-01-11 11:05
Not the same!
`/tag` with `/tag/other` will all be actived, if not set `exact = true`, that's right! But
like `/tagxxx/` will be actived too, it's not very suitable.
And also I set the `exact=true`, they(`/tag` `/tagxxx`) will be all actived too! So I think this is a bug! Please check it.
You can see the demo, the path `/usersa`: https://jsfiddle.net/8xrk1n9f/28/

**Comment by posva** [comment] 2017-01-11 11:25
it's not a bug, please, read the docs I sent you:

> The default active class matching behavior is inclusive match. For example, <router-link to="/a"> will get this class applied as long as the current path starts with /a.

**Comment by muei** [comment] 2017-01-11 11:48
I'v readed it, ok. I hope '/a' not match '/axxx', can match '/a/xxx/xxx'. @yyx990803

**Comment by yyx990803** [comment] 2017-01-17 14:27
Yeah, `/usera` should not make `/user` links highlighted.

**Comment by lukepolo** [comment] 2017-01-17 22:19
I just ran across this issue as well 

http://codepier.dev:3000/site/1/
http://codepier.dev:3000/site/14/

Both are marked as active links

**Closed as completed** 2017-01-18 19:29 UTC
Labels: bug
