### ISSUE TITLE
Allow reloading of the current route when clicked

### ISSUE THREAD

**Issue by boycce** [vuejs/vue-router#2957] opened 2019-10-07 20:49 UTC
### What problem does this feature solve?
I think it's important for `vue-router` to try mimic native browser for such as when dealing with links being clicked.  Adding an option to allow the current route being reloaded when clicked would allow any API requests to be re-fetched that located under the navigational guards (beforeEach, beforeRouteEnter, etc)

### What does the proposed API look like?
Maybe include a router instance option to allow for this behaviour

**Comment by posva** [comment] 2019-10-07 21:06
Duplicate of https://github.com/vuejs/vue-router/issues/974

**Closed as completed by posva** 2019-10-07 21:06 UTC

**Comment by boycce** [comment] 2019-10-07 21:21
Yes and also a duplicate of #2430 
Many developers are still left with inconclusive and convoluted answers when trying to provide their users with a native browser behaviour while using navigational guards. Imagine the frustration if browsers removed this feature.

**Comment by posva** [comment] 2019-10-08 07:30
If you know it was a duplicate, please don't open a new issue...

**Comment by boycce** [comment] 2019-10-09 03:54
Apologies, I didn't realise that #974 was still open, I just saw that it was opened 3 years ago and assumed it was closed.
