### ISSUE TITLE
scrollBehavior should allow configuring scrolling element

### ISSUE THREAD

**Issue by phouri** [vuejs/vue-router#2777] opened 2019-05-22 06:44 UTC
### What problem does this feature solve?
A lot of times - the scrolling element in the document is not the window, making scrollBehavior not work (and the saved position too probably). 

Should allow setting the scrolling element in the application (not sure if as a global, or per scrollBehavior function or both).

##### Global Option:

When initiating Vue router - allow setting scrollingElement property that will replace window.

##### Per Scroll Behavior Option:

When returning the scroll object should allow to set scrollingElement that will override the window (or the global config).

savedPosition should always be related to the global config (or window).

**Comment by posva** [comment] 2019-05-22 15:29
Duplicate of https://github.com/vuejs/vue-router/issues/1187

**Closed as completed by posva** 2019-05-22 15:29 UTC
