### ISSUE TITLE
ability to add subroutes to already registered routes

### ISSUE THREAD

**Issue by piotrek-horodenski** [vuejs/vue-router#2542] opened 2018-12-20 17:27 UTC
### What problem does this feature solve?
This feature solves lazy loading problems in big applications, where we don't even want all routes to be registered for unauthorized users. 

### What does the proposed API look like?
It could be based on named routes - only named route could have its children list extended.
`router.addRoutes` when called with 2 arguments `(name, route[])`, would seek for named route by `name` and add route[] to its children

**Comment by posva** [comment] 2018-12-20 17:30
duplicate of #1156

**Closed as completed by posva** 2018-12-20 17:30 UTC

**Comment by piotrek-horodenski** [comment] 2018-12-20 17:33
it's a duplicate of https://github.com/vuejs/vue-router/pull/2064
