### ISSUE TITLE
transition nested keep-alive  and keep-alive deeply nested router-views display the last visited component component

### ISSUE THREAD

**Issue by santiaomaojin** [vuejs/vue-router#3015] opened 2019-11-01 10:28 UTC
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/santiaomaojin/Ly3cgq8r/14/](https://jsfiddle.net/santiaomaojin/Ly3cgq8r/14/)

### Steps to reproduce
1. click export
2. click workbench
3.click customerSummary 

### What is expected?
customerSummary component render

### What is actually happening?
export component render

---
when i delete transiton component，it's ok，but wen i use transition component. it is bad

**Comment by posva** [comment] 2019-11-01 18:20
Duplicate of https://github.com/vuejs/vue-router/issues/1242

**Closed as completed by posva** 2019-11-01 18:20 UTC
