### ISSUE TITLE
router-view do not return vnode but returned other

### ISSUE THREAD

**Issue by FoxDaxian** [vuejs/vue-router#2910] opened 2019-08-26 09:35 UTC
### Version
3.1.2

### Reproduction link
sorry, this options could Meet my needs.

### Steps to reproduce
in the case of node ssr, i have codes below:

router.js
```javascript
import Vue from 'vue';
import Router from 'vue-router/dist/vue-router.common';

Vue.use(Router);

const Foo = {template: '<div>foo</div>'};

export function createRouter() {
    const router = new Router({
        mode: 'history',
        base: '/demopage',
        routes: [
            {
                path: '/home/test',
                component: Foo
            }
        ]
    });
    return router;
}
```
index.js

```javascript
import index from './app';
import Vue from 'vue';
import {createRouter} from './router';

const createApp = () => {
    const router = createRouter();
    const app = new Vue({
        render: h => h(index),
        router
    });
    
    return {app, router}
};

createApp().app.$mount('#app');
export default createApp;
```

app.js
```javascript

export default {
    methods: {
        click() {
            this.$router.push('/home/test');
        }
    },
    render() {
        return (
            <div id='app'>
                <div class='routerviewwrap'>
                    <router-view />
                </div>
                <button onClick={this.click}>jump</button>
            </div>
        );
    }
};

```

### What is expected?
when click button, view should be show 'foo' in the routerviewwrap element, but not.

### What is actually happening?
when click button, view show html comment 'function(t,n,r,o){return Le(e,t,n,r,o,!0)}' in the routerviewwrap element

**Comment by posva** [comment] 2019-08-26 09:41
Couldn't reproduce: https://jsfiddle.net/9fzws71c/
Please provide a boiled down repro and I will take a look. Closing until one is provided

**Closed as completed by posva** 2019-08-26 09:41 UTC

**Comment by FoxDaxian** [comment] 2019-08-26 10:52
above code on the node koa ssr context, so I don't know how to reproduce for you, but i can support gif. 
![gif](https://raw.githubusercontent.com/FoxDaxian/FoxDaxian.github.io/master/assets/picgo/20190826185003.gif)

**Comment by posva** [comment] 2019-08-26 11:26
A boiled down reproduction in a git repository can make it
