### ISSUE TITLE
The addRoutes  method need to suport  adding dynamic routes as children to an existing route

### ISSUE THREAD

**Issue by hzsrc** [vuejs/vue-router#2622] opened 2019-02-22 05:26 UTC
### What problem does this feature solve?
The addRoutes method currently only suport add new routes to root routes.  But if can not add routes as children to an existing route.

### What does the proposed API look like?
router.addRoutes(routes: Array<RouteConfig>, parent ? : Location)

Like:
router.addRoutes([...childRoutes],  '/main')

**Comment by posva** [comment] 2019-02-22 13:25
Duplicate of #1156

**Closed as completed by posva** 2019-02-22 13:25 UTC
