### ISSUE TITLE
Allow router-link click events to bubble up

### ISSUE THREAD

**Issue by tmorehouse** [vuejs/vue-router#1374] opened 2017-04-26 00:47 UTC
### What problem does this feature solve?
when a `<router-link>` appears in a dropdown menu, the menu is not alerted of the click and stays open.

### What does the proposed API look like?
Possibly a new `<router-link>` prop to enable event bubbling maybe call it `bubble`, which defaults to `false` to keep current compatibility.

**Comment by posva** [comment] 2017-04-26 08:43
Are you sure it's not the dropdown menu that is stopping propagation?

**Comment by tmorehouse** [comment] 2017-04-26 14:17
I'll make a fiffle up with a basic example.

But you can try by just adding  an `@click` handler on the router link and it will never get fired.

**Comment by tmorehouse** [comment] 2017-04-26 16:54
Here is a fiddle that demonstrates that clicks on `<router-link>` do not bubble up (even with .defaultPrevented set).  

Clicking on a regular `a` using the hash method works.

https://jsfiddle.net/tmorehouse/bwuug3o4/

Dropdown menu's rely on the click event to close the menus, and if they can't be listed to, then they will not close.

I am not sure if there is another way to detect this.  Or maybe if say the prop `bubble` were introduced that would instruct the `<router-link>` to `$emit` an event `click`

**Comment by simplesmiler** [comment] 2017-04-26 17:54
`v-on` [does not](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components) listen for native events when used on a component (e.g. `router-link`). But there's a `.native` modifier that allows to do that. Fixed demo: https://jsfiddle.net/bwuug3o4/1/

Closing, as this is not a bug.

**Closed as completed by simplesmiler** 2017-04-26 17:54 UTC
Labels: need repro

**Comment by tmorehouse** [comment] 2017-04-26 18:02
yeah, after playing around a bit more, if I listen for both `@click="onCllick"`, and `@click.native="onClick"` I can get it to work for both `<router-link>` and regular `<a href="...">` elements in dropdown menus.

**Comment by tmorehouse** [comment] 2017-04-26 18:04
Maybe adding a note to the `<router-link>` documentation about `@click` handlers would be great.

**Comment by Little-Fan** [comment] 2018-01-05 03:31
@tmorehouse  谢谢你，确定可以用@click.native="onClick"  来触发 <router-link>标签的单击事件，如果用@click="onCllick" 是不会触发 <router-link>标签 单击事件的。
