### ISSUE TITLE
Bootstrap breaks routing

### ISSUE THREAD

**Issue by Lidbetter** [vuejs/vue-router#24] opened 2015-06-22 02:57 UTC
When passing in `{ hashbang: true }` to the router the following occurs:
* v-link do not generate #! urls
* The router does not respond to the #! urls, only regular paths

```html
<div id="app">
  <a v-link="dragon">Dragon</a>
  <router-view v-transition="fade" transition-mode="out-in"></router-view>
</div>
```

```js

var App = Vue.extend({

    template: '<div v-link="dragon">Dragon</div><router-view></router-view>',

    components: {
        dragon: {
            template: 'here be dragons'
        }
    }
});
var router = new VueRouter({
    hashbang: true
});

router.map({
    'dragon': {
        component: 'dragon'
    }
});
router.start(App, '#app');
```

Expected behaviour:
```
url: example.com
shows a link with dragon

clicking the 'dragon' link changes the URL to 'example.com/#!/dragon'
'here be dragons' is now shown below the 'dragon' link
```

Current behaviour:
```
url: example.com
shows a link with dragon

clicking the 'dragon' link changes the URL to 'example.com/dragon'
'here be dragons' is now shown below the 'dragon' link
```

**Comment by yyx990803** [comment] 2015-06-22 14:06
I don't see this problem with the latest build. Are you sure you are not using the outdated files in `dist`?
Also, `hashbang` defaults to true.

**Comment by Lidbetter** [comment] 2015-06-22 14:59
I built from source yesterday afternoon (EST).

In the project I am using vue 0.12.1 & vue resource dist, bootstrap js and jquery.

I will clone again and rebuild later and test without bootstrap (I think that has some interaction with the url to do tab switching etc.) which seems like it is at least possible that is interfering

**Comment by Lidbetter** [comment] 2015-06-22 23:35
The current router is incompatible with bootstrap js - including it on the same page as vue-rotuer breaks #! routing

`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
`

**Comment by yyx990803** [comment] 2015-06-23 18:10
I honestly don't understand why Bootstrap would interfere with routing...

**Comment by yyx990803** [comment] 2015-06-23 18:13
Tested adding jquery & boostrap in example and everything works fine.

**Comment by JeffreyVdb** [comment] 2015-06-23 23:04
Can confirm that it works fine for me as well.

```html
<button class="btn btn-primary btn-block" v-link="/{{activeRegion}}/{{query}}" v-el="queryFind">
    <i class="fa fa-search fa-fw"></i> Find
</button>
```

This is the exact code I'm using, navigates me to the correct URL and browser history works without problems.

my bootstrap version currently on 3.3.4 for reference. I'm using the full bootstrap package so I wouldn't have a clue why it breaks on your end.

**Comment by yyx990803** [comment] 2015-06-23 23:07
@JeffreyVdb thanks for confirming.
@Lidbetter closing as this is pretty unlikely to be caused by Bootstrap - if you are still running into issues, please open a new one with a repro.

**Closed by yyx990803** 2015-06-23 23:07 UTC
