### ISSUE TITLE
"props" option works differently than explained in the docs when defining multiple components on a route, 

### ISSUE THREAD

**Issue by brad426** [vuejs/vue-router#1183] opened 2017-02-20 15:12 UTC
Given a route entry like this:
```
{
  path: '/path/:test_prop',
  components: {
    default: Bar,
    a: Foo
  },
  props: true
}
```
Neither component Foo or Bar will receive the `test_prop` prop

Working example of issue https://jsfiddle.net/6du90epg/231/

**Comment by LinusBorg** [comment] 2017-02-22 09:41
I think this is "only" a problem of lacking documentation.

Looking at the source [here ](https://github.com/vuejs/vue-router/blob/5bc255af0a99e807dd202b16b26ab82e4ffa4707/src/create-route-map.js#L56-L58)and [here](https://github.com/vuejs/vue-router/blob/a4a91e70730fa4008ed7dc8c89e75583ff053164/src/components/view.js#L63), it's clear that the intended usage with multiple components is this:

```javascript
 {
  path: '/multiple/:test_prop',
  components: {
    default: Bar,
    a: Foo
  },
  props: {
    default: true,
    a: (route) => ({ test_prop: route.params.test_prop })
  }
}
```

With that, it works as intended: https://jsfiddle.net/Linusborg/6du90epg/237/

And this makes sense, because in most scenarios, each component will/might need a different set of props.

**Comment by brad426** [comment] 2017-02-22 10:23
Yup, that works perfectly. Thank you.

**Comment by LinusBorg** [comment] 2017-02-22 10:24
Re-opened because we still have to track improvement of docs here. ;)

**Comment by LinusBorg** [comment] 2017-02-23 12:52
merged imrpoved docs section, have to republish again tonight, though.

**Closed as completed** 2017-04-06 05:16 UTC
Labels: improvement, docs, 2.x

**Comment by veonua** [comment] 2018-12-28 16:41
```
{
      path: '/a',
      components: {
        default: Reader,
        toolbar: ReaderToolbar
      },
      props: { 
        default : (route) => ({ url: route.query.u, card_ref: route.query.r }), 
        toolbar : (route) => ({ url: route.query.u, card_ref: route.query.r })
      } 
    }
```

ReaderToolbar got no props
