### ISSUE TITLE
Add ability to change URL upon specific actions

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue-router#671] opened 2016-09-21 15:13 UTC
I love using vue-router, however sometimes feel it'd be nice to have a little more control over routing changes. At the moment, there doesn't seem to be a simple way to change to a different route _without_ navigating to a new page component.

For example: I have a list of orders in a list, with each list item clickable. On click, a modal opens and shows more information about that order. Currently, because opening the modal occurs within the same page component (`Orders.vue`), the URL remains as `/orders`. However, it'd be nice to be able to change the URL to `/orders/:order_id` when the modal is opened (and navigate back to `/orders` when closed).

My main use-case is to allow the linking of resources between pages. Allowing someone to navigate straight to `/orders/123` and having a modal open with the information would be ideal.

This may be possible with the current version of vue-router, but I'm not aware of it. If not, would this be something worth implementing?

Thanks!

**Comment by Centaur** [comment] 2016-09-22 02:18
The whole point of using a router is to let it manage url change for you, and all replayable page states should be reflected in the route path. In your case , you can define the state of an opened modal dialog as a nested subroute of `/orders`, or as a sibling route with some [meta](https://github.com/vuejs/vue-router/blob/next/docs/en/advanced/meta.md) field.  I suggest you read more of the [documentation](https://github.com/vuejs/vue-router/tree/next/docs/en) and the [examples](https://github.com/vuejs/vue-router/tree/next/examples).

**Comment by LinusBorg** [comment] 2016-09-22 07:30
Closing this as it's not a bug. 

For further support, we encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Closed as completed by LinusBorg** 2016-09-22 07:30 UTC
