### ISSUE TITLE
beforeRouteEnter & beforeRouteLeave not working when route component created with Vue.extend

### ISSUE THREAD

**Issue by budiadiono** [vuejs/vue-router#818] opened 2016-10-21 14:13 UTC
`beforeRouteEnter` and `beforeRouteLeave` event not triggered when the route component is created using `Vue.extend`.  

See: https://jsfiddle.net/budiadiono/76sgL1ee/4/

**Comment by LinusBorg** [comment] 2016-10-21 15:27
It seems assumes that `extractEnterGuards` plain options objects are used:

https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L167

**Comment by victorwpbastos** [comment] 2016-10-27 17:30
Not working when defined in global mixins too.

**Comment by senomorii** [comment] 2016-10-31 04:38
@victorwpbastos +1

**Comment by lbineau** [comment] 2016-10-31 13:03
+1

**Comment by SaidTayebi** [comment] 2016-11-04 09:18
I believe it doesn't work in Single File Component eigther.

**Comment by LinusBorg** [comment] 2016-11-04 09:24
> I believe it doesn't work in Single File Component eigther.

That would be odd, as SFCs generally export simple options objects (which do work).

Any reproduction available?

**Comment by sagarrabadiya** [comment] 2016-11-10 05:26
it works in single file component, but only if hook is defined inside component itself, otherwise not working for ex. if defined in mixin or in extended component its not working.

**Comment by yyx990803** [comment] 2016-11-12 23:15
fixed in a5554a8

also, mixins usage are fixed in fb32ccb

**Closed as completed by yyx990803** 2016-11-12 23:15 UTC
Labels: bug, 2.x

**Comment by JTallis** [comment] 2016-12-04 09:42
I seem to be having an issue with this. I've tried beforeEnter two ways: In the routes definition, and in the component file.

```js
const routes = [
    { path: '/', component: require('./components/example.vue') },
    { path: '/guestbook', component: require('./components/guestbook.vue') },
    {
        path: '/login',
        component: require('./components/login.vue'),
        beforeEnter: (to, from, next) => {
            console.log('test');
            next();
        }
    },
    { path: '/register', component: require('./components/register.vue') },
];
```

```html
<template></template>

<script>
    module.exports = {
        beforeRouteEnter (to, from, next) {
            console.log('before enter');
            next();
        }
    }
</script>
```

Neither of them want to execute. Am I doing something obviously wrong here? The routes work fine as do the components just not the before enters.

**Comment by imac8t** [comment] 2017-03-04 15:13
@sagarrabadiya beforeRouteUpdate doesn't work in Single file component 
vue 2.2
vue-router 2.3.0

**Comment by LinusBorg** [comment] 2017-03-04 15:37
Please don't re-use 4 months old, closed issues.

**Comment by jaywhy13** [comment] 2018-01-31 03:43
I'm having this issue as well.
vue 2.5.4
vue-router 3.0.1

No matter what I do, beforeRouteUpdate never gets called. In my case I'm using the webpack loader setup.

**Comment by LinusBorg** [comment] 2018-01-31 07:30
Locking this issue since my first request obviously wasn't dead
