### ISSUE TITLE
Suggest `router.history.length`

### ISSUE THREAD

**Issue by xqyww123** [vuejs/vue-router#1010] opened 2016-12-12 11:36 UTC
I'm working on a login page which should return to last page if exists or home page, when login success.  `router.go` is a good way but it always return `undefined` whenever success or not. So that I wonder a way to detect whether last page existed in history, or some thing about length of history. `window.history.length` is an available approach currently ( ONLY tested in `hash` mode ), but I'm expecting a formal API.

**Comment by LinusBorg** [comment] 2016-12-12 16:22
I think your request is a duplicate of #883 - can you verify?

I think this would be a useful feature and I think we will implement it.

**Comment by LinusBorg** [comment] 2016-12-17 15:51
Will close this as a duplicate - please comment if you think I was wrong.

**Closed as completed by LinusBorg** 2016-12-17 15:51 UTC
Labels: duplicate, feature request, 2.x
